- setup.py
Fix encoding compatibility in setup. will create a post release for 0.2.0 post0
> fix encoding compat

- tests/unittest/test_beam_search.py
> Used fixed seed for test_beam_search

- env/doc.yml
Specify the pandoc version to 2.2
> fix pandoc

- env/doc.yml
> fix pandoc version

- docs/examples/language_model/get_ptb_data.sh
- env/doc.yml
> update ptb link

- gluonnlp/model/block.py
Fix docstring of L2Normalization
> Docstring L2Normalization

- gluonnlp/loss/__init__.py
- gluonnlp/loss/activation_regularizer.py
- gluonnlp/model/__init__.py
- gluonnlp/model/language_model.py
- gluonnlp/model/train/cache.py
- gluonnlp/model/train/language_model.py
Fix language model and loss docs
> Fix language model and loss docs

- gluonnlp/data/utils.py
> minor doc fix

- docs/api/model.rst
- docs/api/model.train.rst
- gluonnlp/model/__init__.py
- gluonnlp/model/train/__init__.py
- gluonnlp/model/train/cache.py
- scripts/language_model/cache_language_model.py
- scripts/nmt/gnmt.py
- scripts/nmt/loss.py
- scripts/nmt/transformer.py
- scripts/word_embedding_evaluation/word_embedding_evaluation.py
- tests/unittest/test_models.py
Move cache model location
Fix pylint
> Move cache model location

- scripts/nmt/train_transformer.py
This pr fixes average sgd in transformer.
> fix average sgd in transformer

- scripts/nmt/machine_translation.rst
- scripts/nmt/train_transformer.py
> update transformer results and fix script

- scripts/language_model/word_language_model.py
Fix the parameter sharing using save_params and load_params between instances with the same parameter structure.
> Fix language model script

- scripts/nmt/bleu.py
- scripts/nmt/machine_translation.rst
This pr adds recursive splitting on compound words. 
> fix split compound words and wmt16 results

- scripts/nmt/train_transformer.py
> fix small bug

- Jenkinsfile
- README.rst
- codecov.sh
Code coverage reports were previously generated on the CI and displayed in the CI logs but not uploaded to https://codecov.io/gh/dmlc/gluon-nlp.
- Upload code coverage reports to https://codecov.io/gh/dmlc/gluon-nlp
> Enable codecov report uploading

- Jenkinsfile
- env/doc.yml
- env/py2.yml
- env/py3.yml
> clean up pandoc in pip

- gluonnlp/data/translation.py
- scripts/nmt/gnmt.py
- scripts/nmt/machine_translation.rst
- scripts/nmt/train_gnmt.py
- scripts/nmt/train_transformer.py
Add transformer result on WMT14 newstest2014 in test-full.tgz.
The previous gnmt result is buggy and was tested on clipped test sequences. Now it is fixed.
> Update Transformer and GNMT result

- scripts/nmt/machine_translation.rst
- scripts/nmt/train_transformer.py
> Fix small bugs in parser

- Jenkinsfile
- env/doc.yml
> clean up before build

- Jenkinsfile
- docs/conf.py
- env/doc.yml
- env/py2.yml
- env/py3.yml
- env/pylint.yml
> Update doc dependencies

- gluonnlp/data/batchify.py
- tests/unittest/test_batchify.py
The previous batchify.Stack() has not kept the input dtypes.
> [Bugfix] Fix batchify bug

- gluonnlp/model/attention_cell.py
Luong style attention should make sure that the projected query has the same dimension as the key, otherwise batch_dot will have dimension mismatch.
- add dimension assert for Luong style attention
> attention assert

- docs/api/data.batchify.rst
- gluonnlp/data/batchify.py
- scripts/nmt/train_gnmt.py
- scripts/nmt/train_transformer.py
- tests/unittest/test_batchify.py
add dtype to batchify function
> add dtype to batchify function

- Jenkinsfile
> Update for conda 4.4

- Jenkinsfile
- Makefile
- env/pylint.yml
Add flake8 to CI. Also see #213.
> Add Flake8

- gluonnlp/_constants.py
- gluonnlp/embedding/token_embedding.py
- tests/unittest/test_vocab_embed.py
Add pretrained Word2Vec embeddings
> Add pretrained Word2Vec embeddings

- Jenkinsfile
Deploy stage may fail randomly due to an unknown bug in nbsphinx or notedown. Retry it up to 3 times before failing the pipeline step.
> Retry CI Deploy step up to 3 times

- .coveragerc
- Jenkinsfile
This PR adds some explicit configuration for the coverage.io CI stage. Previously the coverage report was sometimes buggy (e.g. https://github.com/dmlc/gluon-nlp/pull/239). This hopefully improves that.
> Add .coveragerc config file

- gluonnlp/data/batchify.py
As title. Thanks @sravanbabuiitm for pointing it out.
> Fix module name in batchify.py example

- scripts/nmt/dataset.py
- scripts/nmt/train_gnmt.py
- scripts/nmt/train_transformer.py
- scripts/tests/test_scripts.py
The current script is prone to error due to the api/base code change. To ensure the script can run properly without making error. This pr adds test for scripts in CI. 
A small translation dataset TEST is created for this purpose. The test code for scripts is added to scripts/tests/test_scripts.py.
> Add test for nmt scripts

- tests/unittest/test_datasets.py
Let's give conll2004 data server some more time to fix on their end.
> Skip test until 8.16

- env/doc.yml
- env/py2.yml
- env/py3.yml
- gluonnlp/model/utils.py
- tests/unittest/test_models.py
fix weight drop with new mxnet version
- resolves #264
> fix weight drop and add tests

- env/doc.yml
- env/py2.yml
- env/py3.yml
- gluonnlp/model/utils.py
> fix warning.warn

- gluonnlp/model/language_model.py
- gluonnlp/model/sampled_block.py
- gluonnlp/model/train/language_model.py
- tests/unittest/test_models.py
Fix a few hard coded places that causes param sharing / hybridization to fail. We also need to update the param name in the pretrained model once I'm done retraining the model..
> fix big rnn eval hybridization and sparse_grad=False

- gluonnlp/base.py
- gluonnlp/data/sampler.py
- gluonnlp/data/stream.py
- gluonnlp/data/word_embedding_training.py
- scripts/word_embeddings/candidate_sampler.py
- scripts/word_embeddings/data.py
- scripts/word_embeddings/evaluate_pretrained.py
- scripts/word_embeddings/extract_vocab.py
- scripts/word_embeddings/stream.py
- scripts/word_embeddings/train_fasttext.py
- scripts/word_embeddings/utils.py
- scripts/word_embeddings/word_embeddings.rst
- tests/unittest/test_datasets.py
- tests/unittest/test_stream.py
This adds Wikipedia Corpus Stream for embedding training script based on #235.
> Add Wikipedia dump streams and ContextStream

- README.rst
Fixing minor typos
langauge -> language
an standard -> a standard
> Fixing Typos in Readme

- gluonnlp/data/dataloader.py
- scripts/tests/test_scripts.py
- tests/unittest/train/test_dataloader.py
Fix #274
- update sharded dataloader
> Update sharded dataloader based on the change of dataloader

- gluonnlp/model/sampled_block.py
> Update doc rendering for sampled_block

- contributor.rst
> update contributor list

- scripts/sequence_sampling/sequence_sampling.rst
> fix scripts doc formatting

- gluonnlp/data/corpora/google_billion_word.py
- gluonnlp/data/utils.py
- gluonnlp/model/language_model.py
- scripts/language_model/language_model.rst
Tested on master branch with test ppl 43.72. 
> update gbw model after transform API refactoring

- scripts/classification/evaluation.py
> Adding evaluation.py for fasttext classification script

- env/doc.yml
- env/py2.yml
- env/py3.yml
- gluonnlp/data/dataloader.py
Update SharedDataLoader based on https://github.com/apache/incubator-mxnet/pull/12177
- Simplify _ShardedMultiWorkerIter
This must not be merged before apache/incubator-mxnet#12197 is fixed as we otherwise have code that relies on mxnet<=1.3.0b20180810 and code that relies on mxnet>=1.3.0b20180815
> Simplify shared dataloader based on recent update on mxnet dataloader

- README.rst
- docs/how_to/contribute.rst
> add community link

- scripts/word_embeddings/word_embeddings.rst
- Thanks @szha for pointing out the formatting issue
> Fix code block formatting in word_embeddings.rst

- scripts/language_model/large_word_language_model.py
> large language model doc update

- Jenkinsfile
- codecov.yml
- env/py2.yml
- env/py3.yml
- scripts/tests/test_encoder_decoder.py
- scripts/tests/test_question_answering.py
- scripts/tests/test_scripts.py
- tests/unittest/batchify/test_batchify.py
- tests/unittest/batchify/test_batchify_language_model.py
- tests/unittest/test_attention_cell.py
- tests/unittest/test_candidate_sampler.py
- tests/unittest/test_convolutional_encoder.py
- tests/unittest/test_datasets.py
- tests/unittest/test_highway.py
- tests/unittest/test_models.py
- tests/unittest/test_pytest.py
- tests/unittest/test_sampled_logits.py
- tests/unittest/test_sampler.py
- tests/unittest/test_sequence_sampler.py
- tests/unittest/test_stream.py
- tests/unittest/test_transforms.py
- tests/unittest/test_vocab_embed.py
> run tests in parallel

- Jenkinsfile
> update jenkins to fail fast

- scripts/tests/test_scripts.py
> Enable word_embeddings/evaluate_pretrained.py test on CI

- scripts/language_model/cache_language_model.py
- scripts/language_model/language_model.rst
fix cache language model script bugs
> fix cache bugs

- scripts/nmt/machine_translation.rst
Add links to pretrained Transformer model on machine_translation.rst
> Add links for pre-trained Transformer model on NMT script page

- gluonnlp/_constants.py
- tests/unittest/test_vocab_embed.py
> fastText crawl-300d-2M-subword

- scripts/nmt/__init__.py
The previous one cannot be converted to ipynb.
> [WIP] Fix GNMT Notebook

- Makefile
- docs/conf.py
enable "edit on github" button
> enable edit on github link

- scripts/nmt/bleu.py
- scripts/nmt/train_transformer.py
- scripts/tests/test_bleu.py
- scripts/tests/test_scripts.py
Fix https://github.com/dmlc/gluon-nlp/issues/349
> Fix encoding for py2

- Jenkinsfile
- docs/examples/sentiment_analysis/sentiment_analysis.md
- env/doc.yml
- env/py2.yml
- env/py3.yml
- env/pylint.yml
clear sentiment analysis notebook
> fix doc build

- README.rst
update expired slack link with a permanent invite link
> update slack link

- scripts/adaptive_softmax/adaptive_softmax.py
- scripts/adaptive_softmax/data/makedata-text8.sh
- scripts/adaptive_softmax/main.py
- scripts/adaptive_softmax/model.py
2018 Geekthon Camp, Beijing. 
Implementation of 'Efficient softmax approximation for GPUs' via MXNet.
Experiments on data set 'Text8' have been conducted and the results are similar to that reported 
from the publication.
The code is written by Duo Zeng, who is a student from Technical University of Munich.
This task is supervised by Haibin Lin, who works in AWS NLP group.
The complete test case is added in '/gluon-nlp/scripts/adaptive_softmax'
> adaptive softmax

- Jenkinsfile
- ci/step_documentation.sh
- ci/step_unit_test.sh
- docs/api/notes/data_api.rst
- docs/api/notes/sequence_sampling.rst
- docs/api/notes/vocab_emb.rst
- env/doc.yml
- env/py2.yml
- env/py3.yml
make api notes link rich as follow-up of #357 comment
> make api notes link rich

- gluonnlp/_constants.py
Fixes #329
@szha please help to copy `s3://lllausen-data/wiki-news-300d-1M-subword-c8853bda.bin` to the GluonNLP bucket before merging.
> Add wiki-news-300d-1M-subword-c8853bda.bin

- gluonnlp/data/dataset.py
- tests/unittest/test_datasets.py
Concatenate multiple datasets; datasets can be of different classes.
> ConcatDataset

- gluonnlp/model/language_model.py
- gluonnlp/model/train/language_model.py
- scripts/language_model/word_language_model.py
- tests/unittest/test_models.py
Add mixture of softmaxes language model by Zhilin Yang, Zihang Dai, Ruslan Salakhutdinov, William W. Cohen. https://github.com/zihangdai/mos
> add mixture of softmaxes language model

- gluonnlp/__init__.py
> bump up version

- scripts/question_answering/data_processing.py
> Fix a spelling mistake.

- gluonnlp/vocab/vocab.py
Change Vocab constructor from staticmethod to classmethod to handle inheritance.
> Vocab static constructor to classmethod to handle inheritance

- env/doc.yml
- env/py2.yml
- env/py3.yml
- setup.py
- src/gluonnlp/data/transforms.py
- tests/unittest/test_transforms.py
add sentencepiece tokenizer detokenizer
> add sentencepiece tokenizer detokenizer

- ci/step_unit_test.sh
Only the code coverage of serial tests was uploaded
Taken from https://github.com/dmlc/gluon-nlp/pull/389#issuecomment-437005052
> Seperately upload serial / not serial coverage reports

- src/gluonnlp/data/stream.py
For some `DataStream` `s1`, `s2 = s.transform(fn)` will lazily apply `fn` to all elements of `s1` when `s2` is iterated. For this purpose `s.transform(fn)` returns a `_LazyTransformDataStream` object which implements `__iter__` to achieve the behaviour described above.
However, currently _LazyTransformDataStream `__iter__` is implemented with a generator (`yield`). Consequently, when calling `i = iter(s2)`, `iter(s1)` is not called. `iter(s1)` is only called upon `next(i)`. This is bad, as for if s1 is a `PrefetchingStream`, it will only start prefetching once `iter(s1)` is called.
- We should establish a "formal" requirement for all `DataStream`, to call `__iter__` on all wrapped streams if their `__iter__` method is called.
- Will add tests soon
> Fix LazyTransformDataStream prefetching

- Makefile
- docs/examples/machine_translation/dataprocessor.py
- docs/examples/machine_translation/gnmt.md
- docs/examples/machine_translation/transformer.md
- src/gluonnlp/data/sampler.py
simplify transformer notebook.
> simplify transformer notebook

- scripts/machine_translation/train_transformer.py
- scripts/machine_translation/translation.py
Change self.tgt_embed.params to self.tgt_embed[0].params
> Fix tie_weight in nmt

- Makefile
- ci/install_dep.sh
- docs/conf.py
- docs/examples/machine_translation/gnmt.md
- docs/examples/word_embedding/word_embedding_training.md
- docs/how_to/contribute.rst
- env/doc.yml
- env/py2.yml
- env/py3.yml
- scripts/text_classification/index.rst
- src/gluonnlp/data/batchify/batchify.py
- src/gluonnlp/data/registry.py
- src/gluonnlp/data/sampler.py
- src/gluonnlp/data/transforms.py
- src/gluonnlp/data/translation.py
- src/gluonnlp/data/utils.py
- src/gluonnlp/data/word_embedding_evaluation.py
- src/gluonnlp/embedding/evaluation.py
- src/gluonnlp/embedding/token_embedding.py
- src/gluonnlp/model/utils.py
- src/gluonnlp/vocab/vocab.py
> enable linkcheck and doctest

- Jenkinsfile
- Makefile
- ci/step_documentation.sh
enforce link check only on branches as some links have intermittent problems
> enforce link check only on branches

- docs/examples/machine_translation/nmt/transformer.py
- docs/examples/machine_translation/nmt/translation.py
- scripts/machine_translation/index.rst
- scripts/machine_translation/train_transformer.py
- scripts/machine_translation/translation.py
This pr will be valid once the new pretrained model is uploaded to the aws server.
> Fix weight tying in markdown and add assertion

- pytest.ini
- scripts/tests/test_question_answering.py
- scripts/tests/test_scripts.py
- tests/unittest/batchify/test_batchify_language_model.py
- tests/unittest/corpora/test_gbw.py
- tests/unittest/corpora/test_large_text_compression_benchmark.py
- tests/unittest/corpora/test_wikitext.py
- tests/unittest/test_datasets.py
- tests/unittest/test_models.py
- tests/unittest/test_stream.py
- tests/unittest/test_transforms.py
- tests/unittest/test_vocab_embed.py
- tests/unittest/train/test_dataloader.py
mark tests with network and gpu requirements so that it's easier to test gluonnlp in different environments.
resolves #410
> mark tests with network and gpu requirements

- scripts/machine_translation/dataprocessor.py
- scripts/machine_translation/train_gnmt.py
- scripts/machine_translation/train_transformer.py
Fix a small bug about dataset in #403, and put write_sentences function to dataprocessor.py.
> Fix a small bug in #403

- src/gluonnlp/embedding/token_embedding.py
- tests/unittest/test_vocab_embed.py
Add unknown_lookup setter to TokenEmbedding
@Ishitori @szha
> Add unknown_lookup setter to TokenEmbedding

- docs/api/modules/model.rst
- docs/api/modules/vocab.rst
- docs/examples/sentence_embedding/elmo_sentence_representation.md
- setup.py
- src/gluonnlp/__init__.py
- src/gluonnlp/data/transforms.py
- src/gluonnlp/model/bilm_encoder.py
- src/gluonnlp/model/convolutional_encoder.py
- src/gluonnlp/model/elmo.py
- src/gluonnlp/model/highway.py
- src/gluonnlp/vocab/__init__.py
- src/gluonnlp/vocab/elmo.py
- tests/unittest/test_elmo.py
> Elmo tutorial

- docs/api/modules/model.rst
- scripts/bert/finetune_classifier.py
- scripts/bert/index.rst
- src/gluonnlp/model/bert.py
- tests/unittest/test_models.py
- Fixed a few documentation errors
- Fixed a ctx usage in BERT fine-tune script when GPU is not enabled.
@cgraywang @fierceX could you help review? 
> BERT doc fixes and usability enhancement

- src/gluonnlp/vocab/subwords.py
- tests/unittest/test_vocab_embed.py
Adds a missing return statement and adds tests.
> Fix hashing single ngrams in NGramHashes

- env/doc.yml
As title. Otherwise latest version of nbsphinx will fail on CI.
> [CI] Add version upper bound to doc.yml

- scripts/sentiment_analysis/process_data.py
Simplify the data preprocessing code for the sentiment analysis. There is no point in using `multiprocessing` for such small datasets.
> Simplify the data preprocessing code for the sentiment analysis script

- docs/index.rst
> Update gluon tutorial link

- README.rst
> [DOC] Add gluon tutorial link on README.rst

- src/gluonnlp/data/dataset.py
- tests/unittest/test_datasets.py
Add a dataset that load `.npz/.npy` files @szha  @leezu @kenjewu 
Might also be useful for dataset created by https://github.com/dmlc/gluon-nlp/pull/489
> [Feature] Add NumpyDataset

- env/doc.yml
- env/py2.yml
- env/py3.yml
- env/pylint.yml
- scripts/bert/create_pretraining_data.py
- scripts/bert/finetune_classifier.py
- src/gluonnlp/data/dataloader.py
- src/gluonnlp/optimizer/bert_adam.py
fix pylint error due to not freezing pylint-quotes plugin
> [BUGFIX] fix pylint error

- docs/index.rst
- docs/install.rst
add detailed installation guide for installing from master, from source, and dev mode.
> [DOC] detailed installation guide

- src/gluonnlp/data/question_answering.py
fix repeated unzipping in squad dataset
> [BUGFIX] fix repeated unzipping in squad dataset

- docs/examples/sentence_embedding/bert.md
> [DOC] Remove misleading link in BERT tutorial

- scripts/question_answering/data_processing.py
- scripts/tests/test_question_answering.py
- src/gluonnlp/data/question_answering.py
- tests/unittest/test_datasets.py
> [API]add squad2.0

- docs/api/modules/vocab.rst
- scripts/bert/dataset.py
- scripts/bert/utils.py
- src/gluonnlp/data/utils.py
- src/gluonnlp/model/bert.py
- src/gluonnlp/model/utils.py
- src/gluonnlp/vocab/__init__.py
- src/gluonnlp/vocab/bert.py
Added BERTVocab and replaced some string literals in existing bert examples. #492
replaced some string literals in existing bert examples.
> [API]BERTVocab

- src/gluonnlp/metric/__init__.py
- src/gluonnlp/metric/masked_accuracy.py
- tests/unittest/test_metrics.py
Metric used to calculate accuracy for the masked language model task. 
> [Feature] Custom metric for masked accuracy

- scripts/language_model/sampler.py
- src/gluonnlp/data/__init__.py
> [DOC] Update candidate sampler doc

- scripts/word_embeddings/index.rst
Fixes #560 Thanks @junrushao1994
> [DOC] Fix typo in word_embeddings/index.rst

- src/gluonnlp/embedding/token_embedding.py
> [DOC] link fix

- scripts/bert/finetune_squad.py
> [Enhancement] [WIP] use static_shape=True for fixed length data in BERT QA

- scripts/machine_translation/dataprocessor.py
- scripts/tests/test_dataprocessor.py
> [BUGFIX] Fix Data Preprocessing for Translation Data

- docs/examples/sentence_embedding/bert.md
Breakdown the sentence to make sure people pay attention to the later part of it. 
> [DOC] Update preparation doc in bert.md

- env/doc.yml
- src/gluonnlp/data/sampler.py
> [BUGFIX] Fix doc (was: Update sampler.py)

- src/gluonnlp/utils/parallel.py
- tests/unittest/test_utils.py
Use num_workers=0 to make debugging easier.
> [API] Add debug option for parallel

- env/doc.yml
- scripts/tests/test_question_answering.py
- scripts/tests/test_scripts.py
> [CI] speed up tests

- scripts/text_classification/fasttext_word_ngram.py
- scripts/text_classification/index.rst
This script address these issues:
dmlc/gluon-nlp#480
dmlc/gluon-nlp#308
> [BUGFIX] Modifying the FastText Classification training for accurate mean pooling

- docs/index.rst
Add extra resource for people who want to just have a grasp of Gluon before reading any gluonnlp tutorials
> [DOC] Update website with 60-min gluon crash course resource

- docs/index.rst
> [DOC] Fix typo on index page

- scripts/bert/dataset.py
- scripts/bert/embedding.py
- scripts/bert/index.rst
- scripts/tests/test_bert_embedding.py
The goal of this BERT Embedding is to obtain the sentence and token embedding from BERT's pre-trained model. In this way, instead of building and do fine-tuning for an end-to-end NLP model, you can build your model by just utilizing the sentence or token embeddings.
- Don't know how to add tests for scripts
- Related issues: #586
> [SCRIPT] Use BERT to get sentence and tokens embedding

- src/gluonnlp/model/bert.py
- src/gluonnlp/model/transformer.py
- tests/unittest/test_models.py
Relates to https://github.com/dmlc/gluon-nlp/issues/542. Added an extra flag which makes BERTEncoder to put encoding results into the output.
@eric-haibin-lin @kenjewu
> [API] [BERT] BERT return intermediate encodings per layer

- ci/step_documentation.sh
- scripts/machine_translation/dataset.py
- src/gluonnlp/base.py
- src/gluonnlp/data/conll.py
- src/gluonnlp/data/corpora/google_billion_word.py
- src/gluonnlp/data/corpora/large_text_compression_benchmark.py
- src/gluonnlp/data/corpora/wikitext.py
- src/gluonnlp/data/question_answering.py
- src/gluonnlp/data/sentiment.py
- src/gluonnlp/data/transforms.py
- src/gluonnlp/data/translation.py
- src/gluonnlp/data/utils.py
- src/gluonnlp/data/word_embedding_evaluation.py
- src/gluonnlp/embedding/token_embedding.py
- src/gluonnlp/model/bert.py
- src/gluonnlp/model/elmo.py
- src/gluonnlp/model/language_model.py
- src/gluonnlp/model/transformer.py
Add example code for data API
- #405 
- resolves #602
> [DOC] API doc

- Jenkinsfile
- Makefile
- ci/step_doc_test.sh
- env/doc.yml
- env/py2.yml
- env/py3.yml
> [CI] upgrade mxnet to 1.4.0

- scripts/bert/embedding.py
- scripts/bert/index.rst
I'm sorry. I was not carefully reading the documentation. pooled_out is not sent embedding. it is a tensor of pooled representation of the first tokens.
> [BUGFIX] remove sent embedding 

- docs/examples/sentence_embedding/bert.md
- scripts/bert/index.rst
Add more explanation for a few places in the BERT fine-tuning tutorial, specially on the data format and data preprocessing. Preview: http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-622/2/examples/sentence_embedding/bert.html 
@berenluthien could you also help review?
> [DOC] Improve BERT fine-tuning tutorial

- src/gluonnlp/__init__.py
> [DEV] bump up version to 0.6

- docs/index.rst
disable pop up in code example on main page
> [DEV] disable pop up in code example on main page

- scripts/bert/index.rst
As title. Thanks @pengxin99 for spotting it. 
> [DOC] Update command in bert/index.rst

- scripts/bert/index.rst
> [DOC] Add link to pre-training log for BERT

- scripts/bert/compare_tf_gluon_model.py
- scripts/bert/convert_tf_model.py
update paths and imports in bert scripts
> [BUGFIX] update paths and imports in bert scripts

- setup.py
long description doesn't show properly on https://pypi.org/project/gluonnlp/
> [DOC] long description content type; For pypi description.

- scripts/bert/index.rst
- src/gluonnlp/data/utils.py
> [DOC] Fix doc in utils.py

- docs/examples/sequence_sampling/sequence_sampling.md
- env/py3-master.yml
- scripts/bert/run_pretraining.py
- scripts/tests/test_bert.py
fix #660 
Also fixes the test case for BERT so that this can be properly caught. 
> [BUGFIX] Update BERT test and pre-train script

- docs/install.rst
Fix outdated installation guide
> [DOC] Fix outdated installation guide

- docs/api/notes/data_api.rst
> [DOC]specify the batch_size for DataLoader

- Jenkinsfile
- ci/step_unit_test_master.sh
- pytest.ini
- scripts/tests/test_scripts.py
- tests/unittest/test_sequence_sampler.py
address sequence sampler test failure
> [CI] address sequence sampler test problem

- Jenkinsfile
> [CI] update nodes for CI

- ci/jenkins/build_steps.groovy
- codecov.yml
- env/cpu/py3.yml
> [CI] fix codecov

- Makefile
- ci/prepare_clean_env.sh
- scripts/tests/conftest.py
- scripts/tests/test_question_answering.py
use fixture for squad dataset tests. resolves #697
> [CI] use fixture for squad dataset tests

- src/gluonnlp/data/word_embedding_evaluation.py
update url for ws353 to fix CI test problem
> [DATA] update url for ws353

- ci/prepare_clean_env.sh
- scripts/bert/finetune_classifier.py
- scripts/bert/pretraining_utils.py
- scripts/bert/run_pretraining.py
- scripts/bert/run_pretraining_hvd.py
- setup.py
- src/gluonnlp/_constants.py
- src/gluonnlp/utils/__init__.py
- src/gluonnlp/utils/data.py
- src/gluonnlp/utils/parameter.py
- tests/unittest/test_utils.py
Add utils.save_parameters API with s3 uri support. The feature assumes boto3 profile is configured locally, and uses the default file upload API. 
> [Feature] support save params to S3

- docs/examples/sentence_embedding/bert.md
fix typo in docs/examples/sentence_embedding/bert.md
I found mis enter.
> [DOC] tiny typo fixed

- tests/unittest/test_sequence_sampler.py
Should fix https://github.com/dmlc/gluon-nlp/issues/706. 
- Just bug fix
- However, the design of dynamic shape fundamentally conflicts with deferred initialization, which i haven't had ideas to fix.
> [BUGFIX] Temporary fix for HybridBeamSearchSampler

- Makefile
- ci/jenkins/build_steps.groovy
create zipped notebooks for link check
> [CI] create zipped notebooks for link check

- src/gluonnlp/data/conll.py
host conll2004 by ourselves
- resolves #718
> [DATA] redistribute conll2004

- src/gluonnlp/__init__.py
> [DEV] bump up version

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docs/community/index.rst
- tests/unittest/test_transforms.py
- tools/diagnose.py
community related docs and templates
> [DOC] community related docs and templates

- scripts/bert/bert_qa_evaluate.py
- scripts/bert/data/qa.py
- scripts/bert/finetune_squad.py
- scripts/tests/test_scripts.py
- src/gluonnlp/data/question_answering.py
Refactor code to enable per example inference
> [Refactor] Refactor BERT SQuAD inference code

- env/cpu/py2.yml
- env/cpu/py3-master.yml
- env/cpu/py3.yml
- env/gpu/py2.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
This reverts commit 0a0bb6c08563db9a9b6244ee8115fd2562fb7e47.
- After #756, the sphinx build runs into JSONDecodeError from time to time.
> [CI] Revert "[CI] Update CI dependencies (#756)"

- Makefile
- README.rst
- env/cpu/py3.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
> [DOC] Update News

- ci/jenkins/Jenkinsfile_py3-master_gpu_doc
> [CI] Really don't exit pipeline before displaying AWS Batch logfiles

- docs/conf.py
- env/cpu/py3.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
- src/gluonnlp/embedding/token_embedding.py
- tests/unittest/test_datasets.py
> [DOC] Fix sphinx-autorun errors on website

- ci/jenkins/build_steps.groovy
enable timeout in every CI step
> [CI] enable timeout

- docs/api/modules/loss.rst
> [DOC] add missing docs for loss

- docs/api/modules/data.batchify.rst
- src/gluonnlp/data/batchify/batchify.py
- tests/unittest/batchify/test_batchify.py
I find myself again and again creating this silly batchification function. It literally just forward the input, this is very useful when you want to get the input data for logging purposes, in text form.
This came up again here: https://stackoverflow.com/questions/56755384/mxnet-ndarray-with-dtype-string
> add the List batchify function

- ci/jenkins/Jenkinsfile_py3-master_gpu_doc
Previously a wrong source-ref was passed to submit-job.py when running on the
master branch.
> [DOC] Fix website build on master branch

- README.rst
- src/gluonnlp/__init__.py
> [DEV] Version bump

- docs/examples/word_embedding/word_embedding_training.md
- src/gluonnlp/data/word_embedding_evaluation.py
- tests/unittest/test_datasets.py
remove wrong tutorial header level
> [DOC] remove wrong tutorial header level

- README.rst
> [DOC] Add GluonCV/NLP archive

- ci/jenkins/build_steps.groovy
dump linkcheck errors to comments
> [CI] dump linkcheck errors to comments

- ci/jenkins/Jenkinsfile_py3-master_gpu_doc
Same as #829 but merging to branch v0.7.x
> Doc for v0.7.x branch

- docs/api/modules/data.rst
- src/gluonnlp/data/__init__.py
add missing dataset document. resolves #831
> [DOC] add missing dataset document

- README.rst
- docs/index.rst
- docs/install.rst
- env/cpu/py3-master.yml
- env/cpu/py3.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
- scripts/tests/test_scripts.py
- scripts/word_embeddings/evaluation.py
- scripts/word_embeddings/model.py
- scripts/word_embeddings/train_glove.py
- src/gluonnlp/model/utils.py
upgrade mxnet dependency to 1.5.0
> [DOC] upgrade mxnet dependency to 1.5.0

- scripts/bert/pretraining_utils.py
Improve help message of --data and --data_eval arguments.
> [DOC] Improve help message

- scripts/bert/index.rst
Try to use hint blocks in the documentation
> [DOC] Update BERT/index.rst

- scripts/language_model/conversion_utils/compare_pytorch_gluon_model.py
- scripts/language_model/conversion_utils/convert_transformer_xl.py
- scripts/language_model/conversion_utils/utils.py
- scripts/language_model/transformer/__init__.py
- scripts/language_model/transformer/attention_cell.py
- scripts/language_model/transformer/embedding.py
- scripts/language_model/transformer/model.py
- scripts/language_model/transformer/softmax.py
- scripts/language_model/transformer/transformer.py
- scripts/language_model/transformer_xl.py
- scripts/tests/test_transformer_xl.py
- src/gluonnlp/data/batchify/language_model.py
- src/gluonnlp/data/corpora/large_text_compression_benchmark.py
- src/gluonnlp/model/attention_cell.py
- src/gluonnlp/model/bert.py
- src/gluonnlp/model/transformer.py
- tests/unittest/corpora/test_large_text_compression_benchmark.py
This adds the TransformerXL model to the language_modeling scripts. As a first step, converting and working with / evaluating pretrained models published by the author is supported. Training will be added as a next step.
Before merging, the pretrained models must be uploaded to S3 and the evaluation script must be extended for 'enwiki8', 'lm1b', 'text8'. Currently only Wikitext103 was converted.
This PR includes an efficient implementation of Multi-head attention with relative position embedding as well as adaptive embedding and adaptive softmax. All are HybridBlocks, but the latter two should be improved with control flow ops in the future to avoid unnecessary computation. it thus replaces (?) https://github.com/dmlc/gluon-nlp/pull/671 and https://github.com/dmlc/gluon-nlp/pull/255.
For …
> [MODEL] TransformerXL Language Modeling

- env/cpu/py3.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
update button style for tutorials and model zoo
> [WEBSITE] update button style

- env/cpu/py3-master.yml
- env/cpu/py3.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
One of our dependencies apparently dropped their dependency on `boto3` and `scipy`. These are however required for our tests and were missing, causing test failures.
> [CI] Fix CI

- scripts/bert/index.rst
> [DOC] Minor doc updates

- scripts/bert/data/baidu_ernie_data.py
- scripts/tests/test_scripts.py
fix XNLI, LCQMC, ChnSentiCorp dataset download link
> [FIX]fix chnsenticorp dataset download link

- scripts/bert/index.rst
> [DOC] Update download link

- README.rst
> [DOC] Update README.rst

- docs/api/notes/data_api.rst
> [DOC] Update the link in data_api page

- scripts/bert/export.py
- scripts/bert/finetune_classifier.py
- scripts/bert/finetune_icsl.py
- scripts/bert/finetune_ner.py
- scripts/language_model/cache_language_model.py
- scripts/language_model/large_word_language_model.py
- scripts/language_model/transformer_xl.py
- scripts/language_model/word_language_model.py
- scripts/machine_translation/inference_transformer.py
- scripts/machine_translation/train_gnmt.py
- scripts/machine_translation/train_transformer.py
- scripts/natural_language_inference/main.py
- scripts/parsing/parser/evaluate/evaluate.py
- scripts/sentiment_analysis/finetune_lm.py
- scripts/sentiment_analysis/sentiment_analysis_cnn.py
- scripts/sentiment_analysis/text_cnn.py
- scripts/text_classification/fasttext_word_ngram.py
- scripts/text_generation/sequence_sampling.py
- scripts/word_embeddings/evaluate_pretrained.py
- scripts/word_embeddings/train_glove.py
- scripts/word_embeddings/train_sg_cbow.py
- src/gluonnlp/__init__.py
- src/gluonnlp/utils/__init__.py
- src/gluonnlp/utils/version.py
- tests/unittest/test_utils.py
When the script is updated with new features from a gluonnlp version, we shall update the minimum required version for that script. If the installed version does not satisfy, exception will be thrown. 
@dmlc/gluon-nlp-reviewers 
> [Usability] Add version checker to all scripts 

- .github/PULL_REQUEST_TEMPLATE.md
- CODEOWNERS
- ci/jenkins/utils.groovy
> [CI] enable timestamp in CI

- scripts/bert/index.rst
Fix documentation for RoBERTa usage https://github.com/dmlc/gluon-nlp/issues/924 
We will need to refresh the website, too
> [DOC] Fix documentation for RoBERTa usage

- docs/examples/language_model/language_model.md
- docs/examples/machine_translation/gnmt.md
- docs/examples/machine_translation/transformer.md
- docs/examples/sentence_embedding/bert.md
- docs/examples/sentence_embedding/elmo_sentence_representation.md
- docs/examples/sentiment_analysis/sentiment_analysis.md
- docs/examples/sequence_sampling/sequence_sampling.md
- docs/examples/word_embedding/word_embedding.md
- docs/examples/word_embedding/word_embedding_training.md
- src/gluonnlp/utils/version.py
Following the previous PR, add version checkers to tutorials. 
> [Usability] Add version checker to all tutorials

- docs/conf.py
> [DOC] fix sphinx mapping on v0.8 branch

- src/gluonnlp/model/language_model.py
- src/gluonnlp/model/train/__init__.py
- src/gluonnlp/model/train/cache.py
- src/gluonnlp/model/train/language_model.py
Change the language models to hybrid blocks. 
> [Feature] Hybridizable AWDRNN/StandardRNN

- tests/unittest/test_sequence_sampler.py
Remove outdated comment in test file.
#710 forgot to delete it
> Remove outdated comment

- scripts/bert/index.rst
- scripts/machine_translation/index.rst
> [DOC] Remove non-existent arguments for BERT and Transformer

- scripts/tests/test_scripts.py
- tests/unittest/test_datasets.py
Disable SimVerb test for 14 days. people.ds.cam.ac.uk/dsg40/paper/simverb/simverb-3500-data.zip is currently offline.
> [CI] Disable SimVerb test for 14 days

- scripts/bert/export.py
- scripts/tests/test_scripts.py
For some reason the `test_export` test in integration test was not run (?) for previous PRs? @leezu 
Fixing the bug here. 
> [BUGFIX] Fix bugs in BERT export script

- setup.py
tqdm is used in multiple scripts.
> [INSTALL] Declare optional tqdm dependency

- Makefile
- env/cpu/py3-master.yml
- env/cpu/py3.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
- pytest.ini
- scripts/tests/test_models.py
- scripts/tests/test_question_answering.py
- setup.py
- src/gluonnlp/data/transforms.py
- tests/unittest/test_bertvocab.py
- tests/unittest/test_datasets.py
- tests/unittest/test_elmo.py
- tests/unittest/test_models.py
- tests/unittest/test_vocab_embed.py
Improve robustness of our tests so that they can also run in other environments.
> [Tests] Improve test robustness

- docs/conf.py
- scripts/machine_translation/dataprocessor.py
- scripts/machine_translation/train_transformer.py
- src/gluonnlp/data/dataset.py
- src/gluonnlp/data/glue.py
- src/gluonnlp/data/transforms.py
- src/gluonnlp/data/word_embedding_evaluation.py
- src/gluonnlp/model/bert.py
- src/gluonnlp/model/transformer.py
- src/gluonnlp/vocab/subwords.py
- tests/unittest/test_datasets.py
A few small changes to improve readability. No API changes.
Let's try to get such small non-breaking changes in separately from API refactor. Thus it will be easier to review and test.
> [REFACTOR] Improve readability

- scripts/tests/test_scripts.py
- src/gluonnlp/data/word_embedding_evaluation.py
- tests/unittest/test_datasets.py
> Change SimVerb3500 URL to aclweb hosted version

- docs/conf.py
> [DOC] update navbar install

- src/gluonnlp/vocab/vocab.py
> [Fix] Vocab.__repr__ if reserved_tokens or unknown_token is None

- src/gluonnlp/__init__.py
bump version in preparation for 0.9 release
> [RELEASE] bump version in preparation for 0.9 release

- ci/batch/docker/Dockerfile
- env/cpu/py3-master.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- scripts/parsing/parser/biaffine_parser.py
- src/gluonnlp/model/train/cache.py
Nightly release pipelines for cu101-mkl is currently blocked.
Recent CPU builds also failed
> [CI] Use Cuda 10.0 MXNet build

- tests/unittest/test_sequence_sampler.py
HybridBeamSearch doesn't work currently https://github.com/dmlc/gluon-nlp/issues/1020
> Disable HybridBeamSearch tests

- scripts/tests/test_scripts.py
> [CI] MXNet nightly still incompatible with horovod

- ci/prepare_clean_env.sh
> [CI] Explicitly specify CUDA version

- scripts/bert/pretraining_utils.py
- src/gluonnlp/data/word_embedding_evaluation.py
Change SimVerb3500 URL to aclweb hosted version
> [v0.8.x][BUGFIX] Change SimVerb3500 URL to aclweb hosted version

- src/gluonnlp/model/attention_cell.py
- src/gluonnlp/model/train/cache.py
- tests/unittest/test_sequence_sampler.py
avoid using dict for attention cell parameter creation
> [v0.8.x][BUGFIX] avoid using dict for attention cell parameter creation

- env/cpu/py3-master.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- scripts/tests/test_scripts.py
https://lists.apache.org/thread.html/cba5e34a59af5e3ce99bbad912341efef32fb409c022d9239aa2994a%40%3Cdev.mxnet.apache.org%3E
> [CI] Switch source of MXNet nightly build

- scripts/bert/embedding.py
- scripts/bert/finetune_classifier.py
- scripts/bert/index.rst
- scripts/tests/test_scripts.py
Fix a few issues found in the embedding script:
- some documentation is outdated
- params_path is actually not passed to the object
- fix hardcoded indices in text processing
- display actual text used for getting the embedding (after truncation)
- (not a bug) add support for sentence-piece vocab
- (not a bug) drop py2 specific code
> [FIX] Update embedding script 

- docs/community/contribute.rst
[DOC] add section for "Clone the master branch for development"
> [DOC] add section for "Clone the master branch for development"

- src/gluonnlp/model/train/language_model.py
- src/gluonnlp/model/utils.py
Solve the weight drop initialization error. Fixes #1060
> [BUGFIX] Fix the weight drop initialization error

- src/gluonnlp/__init__.py
- src/gluonnlp/model/sampled_block.py
- tests/unittest/test_sampled_logits.py
> [bugfix] Backport int32 fix for sampled block and bump version

- tests/unittest/test_datasets.py
This fix only enables those flaky tests on Monday.
> Add Conditions to Tests that Require Remote Access to 3rd Party Server

- scripts/bert/finetune_classifier.py
- src/gluonnlp/model/bert.py
This reverts commit e88d55e77e55b8e562881ed9d12160053810961b until root-cause of issues is identified / fixed.
Reference https://github.com/dmlc/gluon-nlp/issues/1127
> Revert #1091

- setup.py
Fixes https://github.com/dmlc/gluon-nlp/pull/1063 https://github.com/dmlc/gluon-nlp/issues/1142
> Add 'packaging' to requirements

- mms/README.rst
- mms/bert.py
> Add MMS example

- docs/install/install-include.rst
> Update Installation instructions for source

- docs/community/release.rst
Added:  - Update the installation from source instruction in the release branch
> [DOC] Update release.rst

- src/gluonnlp/__init__.py
Bump master version to 0.10.0.dev
> Dev version bump

- env/cpu/py3-master.yml
- env/gpu/py3-master.yml
The URL scheme recently changed. CC @szha
> Update master build URLs

- README.rst
> [DOC] Add JMLR bib

- docs/api/modules/utils.rst
- src/gluonnlp/utils/seed.py
- tests/unittest/test_utils.py
Fixes #1110 
Added set_seed function in utils.seed.py for setting seed value to enhance reproducibility.
> Add function to set seed 

- src/gluonnlp/vocab/vocab.py
- tests/unittest/test_vocab_embed.py
Fixes https://github.com/dmlc/gluon-nlp/issues/1158 
> [BUGFIX] Fix vocab determinism in py35

- scripts/language_model/transformer/model.py
- src/gluonnlp/data/baidu_ernie_data.py
- src/gluonnlp/data/conll.py
- src/gluonnlp/data/corpora/google_billion_word.py
- src/gluonnlp/data/corpora/large_text_compression_benchmark.py
- src/gluonnlp/data/corpora/wikitext.py
- src/gluonnlp/data/glue.py
- src/gluonnlp/data/intent_slot.py
- src/gluonnlp/data/question_answering.py
- src/gluonnlp/data/sentiment.py
- src/gluonnlp/data/super_glue.py
- src/gluonnlp/data/transforms.py
- src/gluonnlp/data/translation.py
- src/gluonnlp/data/word_embedding_evaluation.py
- src/gluonnlp/utils/files.py
Fix race condition in downloading datasets causing CI failures.
> Fix race condition

- docs/community/index.rst
> [COMMUNITY] update slack invitation link

- setup.py
This pull request is working for #1179 . We want a simpler step for installing dependencies when we want to build the website and this pull request adds all the necessary dependencies.
It also removes unused imports in the head of the file.
> [DEV]Add missing requirements and remove unused imports

- ci/batch/docker/Dockerfile
- env/cpu/py3.yml
- env/docker/py3.yml
- env/gpu/py3.yml
This pull request copies #1208 to the v0.9.x branch
> [DEV] Specify llvmlite version in CI environment to avoid incompatibility with numba

- env/cpu/py3-master.yml
- env/cpu/py3.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
> [DEV] Update dependency on CI build

- src/gluonnlp/model/bert.py
https://github.com/dmlc/gluon-nlp/issues/1183#issuecomment-621659400
> Fix layer_norm_eps in BERTEncoder on 0.9.x

- env/cpu/py3-master.yml
- env/cpu/py3.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
This pull request updates multiple pip packages versions that are dependencies of gluon-nlp
> [DEV] Update pip pakcages versions

- env/cpu/py3-master.yml
- env/cpu/py3.yml
- env/docker/py3.yml
- env/gpu/py3-master.yml
- env/gpu/py3.yml
This pull request updates multiple packages that are dependencies of gluon-nlp.
> [DEV] Update pip package dependencies

- docs/conf.py
Since the old beta version mxnet website is deprecated, we are migrating the intersphinx website to the new, formal website of mxnet.
> [DEV] Update mxnet intersphinx to release site

- .github/workflows/unittests.yml
Unblock CI (eg. https://github.com/dmlc/gluon-nlp/pull/1254)
> Pin mxnet version range on CI

- ci/jenkins/Jenkinsfile_py3-master_gpu_doc
This pull request works together with the previous pull quest #1252 . #1252 works on the python script part and this pull request works on the Jenkins CI part.
They work together to solve the problem from #1230
> [Website]Lift timeout restriction on CI configuration

- .github/workflows/unittests.yml
https://github.com/codecov/codecov-action/issues/80#issuecomment-645189406
> Update codecov action to handle different OS and Python versions

- src/gluonnlp/data/tokenizers.py
- src/gluonnlp/models/__init__.py
- src/gluonnlp/utils/lazy_imports.py
- tests/test_models.py
- tests/test_models_xlmr.py
Adds several fixes to make the CI pass and more stable. I find that XLMR seems to be too large for Github action so I disabled the forward test.
@leezu
> [Numpy][Tiny Fix]Some fixes to make the CI more stable

- src/gluonnlp/models/transformer_xl.py
- tests/test_layers.py
As pointed out in https://github.com/dmlc/gluon-nlp/pull/1261#pullrequestreview-446785733
> Fix parameter share regex

- tools/batch/docker/Dockerfile
- tools/batch/submit-job.py
> [CI] Batch cpu version

- tools/batch/docker/Dockerfile
- tools/batch/docker/README.md
update batch docker and add readme
- this setup is specific to the gluonnlp-dev account.
> [CI] Batch docker update

- src/gluonnlp/__init__.py
Update the version number to have a released version including https://github.com/dmlc/gluon-nlp/commit/9e356b35849f0dc4fac6c7b6b2de7fc72df2d7e1
> Version 0.9.2

- scripts/pretraining/data_preprocessing.py
- scripts/pretraining/run_electra.py
- tools/batch/docker/Dockerfile
Fix electra pretraining script and data preprocessing script
cc @sxjscience
> Fix electra 

- src/gluonnlp/sequence_sampler.py
- tests/test_sequence_sampler.py
make beam search a hybrid block
- currently the model can't be hybridized due to use of in-place op
> [MODEL] make beam search a hybrid block

- README.md
- scripts/benchmarks/benchmark_utils.py
- scripts/machine_translation/train_transformer.py
- setup.py
- src/gluonnlp/data/tokenizers.py
- tests/README.md
- tools/docker/README.md
- tools/docker/ubuntu18.04-devel-gpu.Dockerfile
- Fix README about Docker Installation.
- Support Tensorboard + TensorboardX in Docker
> [Numpy] [Fix] Update README.md

- src/gluonnlp/utils/config.py
Fix the typo in the description of comments
> [DOC] fix typo

- .github/workflows/unittests-gpu.yml
- tools/batch/batch_states/test.sh
> [CI] Fix Source Reference Issues

- .github/workflows/unittests-gpu.yml
- .github/workflows/unittests.yml
> [CI] Update test file path

- ci/jenkins/Jenkinsfile_py3-master_gpu_doc
- env/docker/py3.yml
- env/gpu/py3.yml
```
[2020-08-24T23:38:24.969Z] Traceback (most recent call last):
[2020-08-24T23:38:24.969Z]   File "docs/md2ipynb.py", line 5, in <module>
[2020-08-24T23:38:24.969Z]     import nbformat
[2020-08-24T23:38:24.969Z] ImportError: No module named 'nbformat'
```
> Fix env/docker/py3.yml

- .github/workflows/data-pipeline.yml
- .github/workflows/unittests.yml
- tools/batch/batch_states/test.sh
> [Fix] Fix Codecov

- setup.py
Make sure the installation works on SageMaker Notebook with `conda_python3` kernel.
> [Fix][SageMaker] Make sure that the installation works in SageMaker

- env/gpu/py3-master.yml
- scripts/bert/bertpass_gpu.cc
- scripts/bert/deploy.py
- scripts/bert/finetune_classifier.py
- scripts/bert/finetune_squad.py
- scripts/bert/index.rst
- scripts/bert/setup.py
- scripts/tests/test_scripts.py
* Add example script to deploy BERT
* Add options to better measure performance
* Allow specification of path for exported model
* Add option to use custom graph pass
* Add optimization for MHA in custom graph pass
* Correct bug with input shapes in optimize_for
* correct typo
* fix lint
* fix lint
* Add documentation
* Add documentation for using deploy script
* Correct typo/add spaces in documentation
* Add setup.py to compile pass, update documentation
* Fix bug in path to include dir & fix pylint
* Add unitest for deploy bert script
* change CUDA version in wheel
* test latest wheel
* change path to custom pass library
* fixing trigger custom pass compilation
* fix lint
* fix lint
* Update mxnet pip version
* Only GPU versions changed
* fix lint
* change wheel to include mkl headers
* …
> cherry pick: Deploy BERT model -  Script (#1237)

- scripts/question_answering/README.md
- scripts/question_answering/run_squad.py
- scripts/question_answering/squad_utils.py
- setup.py
- src/gluonnlp/utils/preprocessing.py
- tools/batch/run_batch_squad.sh
Some documentation improvement + Use dataclass
> [Fix] Minor fix for AMLC Tutorial - QA

- scripts/processing/apply_subword.py
- scripts/processing/learn_subword.py
Tell the users where the models will be saved into.
> [Log Message Improvement] Improve nlp process

- scripts/question_answering/run_squad.py
Fix squad to support horovod as https://github.com/dmlc/gluon-nlp/pull/1319 did for pretraining electra
Got a result of 77.62/80.39 for mobilebert. See https://github.com/dmlc/gluon-nlp/tree/master/scripts/question_answering for the comparison
@sxjscience @ZiyueHuang 
> Fix the correctness of the Horovod support on squad

- scripts/machine_translation/gnmt.py
- src/gluonnlp/model/bert.py
- src/gluonnlp/model/seq2seq_encoder_decoder.py
- src/gluonnlp/model/transformer.py
> [MODEL] fix seq2seq encoder input order

- .github/workflows/buildwebsite.yml
- setup.py
> [BUGFIX] Freeze boto3

- src/gluonnlp/vocab/vocab.py
The v0.x vocab implementation uses a custom dict implementation to handle case where unknown tokens are specified. When looking up multiple tokens, it is faster to work with a Python dict directly. A similar change has already been made in the master branch. This change pulls it to the v0.x branch.
Results from a micro benchmark below. Current implementation:
```python
In [4]: v = Vocab({k:1 for k in ['a', 'b', 'c']})
In [5]: %timeit v['a']
854 ns ± 0.819 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
In [6]: %timeit v['abc']
861 ns ± 8.27 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
In [7]: keys=['a', 'c', 'c', 'b', 'c', 'c', 'c', 'c', 'a', 'b'] * 1000
In [8]: %timeit v[keys]
3.98 ms ± 9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
In [9]: v = …
```
> [PERFORMANCE] Improve vocab lookup performance by working with a dict() directly

- src/gluonnlp/vocab/vocab.py
> v0.8.x: Backport #1382

- src/gluonnlp/vocab/vocab.py
> v0.9.x: Backport #1382

- src/gluonnlp/vocab/vocab.py
> v0.10.x: Backport #1382

- scripts/benchmarks/benchmark_utils.py
When I tried to run benchmarks only with CPU I got NaNs in results:
```
2020-10-20 14:11:39,221 - benchmark_utils - INFO - 1 / 1
2020-10-20 14:11:44,714 - benchmark_utils - INFO - Can't pickle local object 'measure_peak_memory_cpu.<locals>.MemoryMeasureProcess'
2020-10-20 14:11:44,732 - benchmark_utils - INFO - Saving results to csv train_fp32_NT_NT/google_en_uncased_bert_base_4_128.csv.
2020-10-20 14:11:44,733 - benchmark_utils - INFO - 
====================            TRAIN - RESULT - SPEED - RESULTS           ====================
2020-10-20 14:11:44,733 - benchmark_utils - INFO - -----------------------------------------------------------------------------------------------
2020-10-20 14:11:44,734 - benchmark_utils - INFO -           Model Name             Batch Size     Seq Length …
```
> [Fix] Gluon-NLP benchmark script fix

- scripts/pretraining/bert/run_pretraining.py
Remove LRScheduler. Since the trainer will dump/load the optimizer (including the LRScheduler), if we use LRScheduler, the learning rate will always be 0 in the phase2 training.
Remove `cfg.MODEL.max_length = max_seq_length`. Since `cfg.MODEL.max_length` is used for the positional embedding and should be 512 (the maximum seq_length of the two phases).
I have trained the BERT base model and finetune on SQUAD 2.0, obtaining 77.89/74.72, which is better than the standard result 76.43/73.59 (https://github.com/dmlc/gluon-nlp/tree/master/scripts/question_answering), since I used the SOP objective instead of NSP (by setting `random_next_sentence` to False) suggested by @sxjscience .
Attached file, [bert_base_logs.zip](https://github.com/dmlc/gluon-nlp/files/5408410/bert_base_logs.zip), contains …
> fix BERT phase2 training

- .github/workflows/unittests-gpu.yml
- tools/batch/submit-job.py
> [CI] Small fixes to increase test logs readability

- README.md
- tests/test_models.py
Fix seed for the TVM test, which can be flaky
> [Fix] Improve test + Move TVM integration to experimental

- .github/workflows/unittests-gpu.yml
- tests/test_models.py
Following the TVM PR, CI is failing with out of memory issues. Test skipping TVM tests.
Reference of CI running out of memory even with an older MXNet commit: https://github.com/dmlc/gluon-nlp/actions/runs/328560026
> Run GPU tests in individual subprocesses

- src/gluonnlp/models/bert.py
- src/gluonnlp/models/model_zoo_checksums/bert.txt
> [Backbone] Add gluon_en_cased_bert_base_v1 pretrained via MLM + SOP

- .github/workflows/unittests.yml
- scripts/pretraining/pretraining_utils.py
- scripts/question_answering/models.py
- src/gluonnlp/attention_cell.py
- src/gluonnlp/layers.py
- src/gluonnlp/loss.py
- src/gluonnlp/models/albert.py
- src/gluonnlp/models/bart.py
- src/gluonnlp/models/bert.py
- src/gluonnlp/models/electra.py
- src/gluonnlp/models/gpt2.py
- src/gluonnlp/models/mobilebert.py
- src/gluonnlp/models/roberta.py
- src/gluonnlp/models/transformer.py
- src/gluonnlp/models/transformer_xl.py
- src/gluonnlp/op.py
- tests/test_attention_cell.py
- tests/test_data_tokenizers.py
- tests/test_embedding.py
- tests/test_gluon_block.py
- tests/test_layers.py
- tests/test_models.py
- tests/test_models_albert.py
- tests/test_models_gpt2.py
- tests/test_models_transformer.py
- tests/test_op.py
- tests/test_sequence_sampler.py
- tests/test_utils_misc.py
- tests/test_utils_parameter.py
update hybrid_forward to use deferred compute
> [MODEL] update hybrid_forward to use deferred compute

- scripts/datasets/general_nlp_benchmark/prepare_glue.py
- scripts/datasets/pretrain_corpus/README.md
- scripts/datasets/pretrain_corpus/prepare_wikipedia.py
- setup.py
- src/gluonnlp/utils/lazy_imports.py
- tests/README.md
- tests/data_cli/test_glue.py
- tests/data_cli/test_prepare_wikipedia.py
- tests/data_cli/test_wikipedia.py
> [Bugfix] Fix prepare_wikipedia

- scripts/pretraining/bert/README.md
> bert readme

- scripts/question_answering/run_squad.py
- src/gluonnlp/attention_cell.py
- tests/test_attention_cell.py
Tiny fix of the amp for log_maskedsoftmax
> [AMP][Bugfix] Fix AMP + SQuAD

- tests/test_attention_cell.py
- tests/test_models.py
Try to fix https://github.com/dmlc/gluon-nlp/issues/1434
> [Fix] Enable the test cases

- README.md
- setup.py
- src/gluonnlp/cli/average_checkpoint.py
- tools/docker/gluon_nlp_job.sh
- tools/docker/ubuntu18.04-cpu.Dockerfile
- tools/docker/ubuntu18.04-gpu.Dockerfile
Update for https://github.com/apache/incubator-mxnet/commit/5dc404dfb0cb5e9a034c9db5d58721e15791ad33
> npx.save -> npx.savez

- .github/workflows/buildwebsite.yml
Fix documentation build workflow. 
> [DOC] Fix docbuild

- .github/workflows/unittests.yml
- setup.py
> [BUGFIX] Fix NumPy version to 1.19.4

- tests/test_gluon_block.py
> Unblock CI by skipping the test

- docs/examples/tokenization/index.rst
- docs/examples/tokenization/tokenization_part3.md
- scripts/processing/learn_subword.py
- tests/process_cli/test_learn_apply_subword.py
Solve issue https://github.com/dmlc/gluon-nlp/issues/1451
> [Preprocess][Tokenizer] Improve learn subword 

- scripts/benchmarks/benchmark_hf.py
Confirmed that FP32 + FP16 + Train + Inference + Torchscript work for transformers>=4.0.0 and pytorch-1.7
> [Fix] Fix an issue introduced in the previous benchmark fix PR.

- scripts/machine_translation/README.md
- scripts/machine_translation/evaluate_transformer.py
> [Doc][Stochastic Beam Search] Improve Documentation of Stochastic Beam Search in NMT

- scripts/conversion_toolkits/convert_fairseq_bart.py
- scripts/conversion_toolkits/convert_fairseq_roberta.py
- scripts/conversion_toolkits/convert_fairseq_xlmr.py
fix fairseq conversion scripts with current upstream
- the config object was moved from the *HubInterface.args to *HubInterface.cfg.model.
> [CONVERTER] fix fairseq conversion scripts

- .github/workflows/data-pipeline.yml
Fix the scheduled test of the data pipeline
> [Scheduled Test] Try to fix data-pipeline scheduled test

- README.md
Update README.md to link to website of the master version
> Update README.md to link to website of the master version

- .github/workflows/buildwebsite.yml
> Fix buildwebsite.yml

- .github/workflows/buildwebsite.yml
- .github/workflows/unittests-gpu.yml
- setup.py
- tools/batch/batch_states/compile_notebooks.sh
Avoid using shell scripts in CI workflow to prevent potential attacks. 
> [CI] Solve CI Vulnerability 

- .github/workflows/buildwebsite.yml
Add checkout step in buildwebsite.yml and make sure new workflow runs normally. 
> [CI] Add checkout step

- .github/workflows/buildwebsite.yml
> [CI] Fix buildwebsite.yml

- .github/workflows/buildwebsite.yml
> [CI] Fix aws wait for object

- scripts/datasets/machine_translation/prepare_wmt.py
- scripts/datasets/pretrain_corpus/prepare_openwebtext.py
- scripts/datasets/pretrain_corpus/prepare_wikipedia.py
- scripts/pretraining/data_preprocessing.py
- scripts/processing/apply_subword.py
- scripts/processing/clean_tok_mono_corpus.py
- scripts/processing/clean_tok_para_corpus.py
use cpu count as default parallelism in data processing
> [SCRIPT] use cpu count as default parallelism

- scripts/pretraining/pretraining_utils.py
- scripts/pretraining/run_electra.py
make electra pretraining runnable again
> [SCRIPT] make electra pretraining runnable again

- .github/workflows/buildwebsite.yml
- tools/batch/batch_states/compile_notebooks.sh
> [CI] Small fix and test new CI on pull request

- scripts/pretraining/pretraining_utils.py
Add the import change was missed when staging my last fix.
> [SCRIPT] fix electra pretraining utils

- src/gluonnlp/utils/misc.py
Try to fix https://github.com/dmlc/gluon-nlp/issues/1522
> [Fix] Fix download

- docs/tutorials/deep_learning_compiler/index.rst
- docs/tutorials/deep_learning_compiler/tvm_basic.md
- docs/tutorials/index.rst
> [Tutorial] Add TVM basic tutorial

- scripts/pretraining/convert_electra_pretrain_backbone.py
- scripts/pretraining/pretraining_utils.py
- scripts/pretraining/run_electra.py
Add script for converting ElectraForPretrain params to backbone
> [SCRIPT] add script for converting ElectraForPretrain params to backbone

- .github/workflows/buildwebsite.yml
- .github/workflows/unittests-gpu.yml
- .github/workflows/unittests.yml
- ci/batch/wait-job.py
- ci/prepare_clean_env.sh
- docs/conf.py
- env/docker/py3.yml
- env/gpu/py3.yml
- src/gluonnlp/model/bert.py
This PR will fix `wait for job and copy files` this step. But for website build, currently the notebook compiling will be submitted to g4 instance, which will raise issue 
```
src/engine/threaded_engine.cc:331: Check failed: device_count_ > 0 (-1 vs. 0) : GPU usage requires at least 1 GPU
```
> [v0.x] Follow up fix for v0.x CI

- .github/workflows/buildwebsite.yml
- ci/batch/compile_notebooks.sh
> [v0.x] Remove Notebook Compiling Steps

- scripts/pretraining/torch/bert/README.md
- scripts/pretraining/torch/bert/prepare_quickthought.py
- scripts/pretraining/torch/bert/run_pretraining.py
- setup.py
- src/gluonnlp/torch/__init__.py
- src/gluonnlp/torch/clib/amp_C_frontend.cpp
- src/gluonnlp/torch/clib/compat.h
- src/gluonnlp/torch/clib/multi_tensor_apply.cuh
- src/gluonnlp/torch/clib/multi_tensor_l2norm_kernel.cu
- src/gluonnlp/torch/clib/multi_tensor_lans.cu
- src/gluonnlp/torch/clib/type_shim.h
- src/gluonnlp/torch/data/__init__.py
- src/gluonnlp/torch/data/batchify.py
- src/gluonnlp/torch/models/bert.py
- src/gluonnlp/torch/optimizers/__init__.py
- src/gluonnlp/torch/optimizers/fused_lans.py
- src/gluonnlp/torch/optimizers/schedules.py
- src/gluonnlp/utils/__init__.py
- src/gluonnlp/utils/shm.py
Add an initial version of the torch pretraining scripts
> Add torch quickthought bert pretraining

- .github/workflows/unittests.yml
> [v0.x] Add Spacy Download in Steps to Pass Unittest

- .pytype.cfg
- docs/examples/sentence_embedding/bert.md
- scripts/parsing/parser/biaffine_parser.py
> [0.x] Update doc

- .github/workflows/unittests-gpu.yml
- .github/workflows/unittests.yml
Remove use of codecov script because of security vulnerability.
https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=2418393&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJtK_k8CRZJGqtO8N-X_uWQbk2p0I-6oYEteb_o2fcdAVxLcDStURXwgxq-dtkZzn8-0eSphtLkp86IrUF8kKu4iNjUwdOT8pLb9IkBx
> [CI][v0.x] remove codecov

- README.md
- docs/install/install-include.rst
- tools/docker/gluon_nlp_job.sh
- tools/docker/ubuntu18.04-cpu.Dockerfile
- tools/docker/ubuntu18.04-gpu.Dockerfile
This switches doc and CI to MXNet 2 Alpha release
> Update for MXNet 2 Alpha

- .github/workflows/buildwebsite.yml
- .github/workflows/unittests-gpu.yml
- .github/workflows/unittests.yml
- ci/batch/compile_notebooks.sh
- ci/batch/submit-job.py
- ci/docker/README.md
- ci/docker/devel_entrypoint.sh
- ci/docker/gluon_nlp_job.sh
- ci/docker/install/install_horovod.sh
- ci/docker/install/install_jupyter_lab.sh
- ci/docker/install/install_llvm.sh
- ci/docker/install/install_openmpi.sh
- ci/docker/install/install_python_packages.sh
- ci/docker/install/install_tvm_cpu.sh
- ci/docker/install/install_tvm_gpu.sh
- ci/docker/install/install_ubuntu18.04_core.sh
- ci/docker/start_jupyter.sh
- ci/docker/ubuntu18.04-cpu.Dockerfile
- ci/docker/ubuntu18.04-gpu.Dockerfile
- setup.py
- tests/unittest/test_models.py
- tests/unittest/test_sampled_logits.py
Create new job queues and job definitions for v0.x branch. The docker files are ported from master branch. 
v0.x GPU docker will be based on nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04, which will unblock some works related to mxnet-cu102==1.8.0.post0
> [v0.x] Port docker from master

- setup.py
- tests/unittest/test_transforms.py
Try to fix unittest by upgrading spacy
> [v0.x] Update spacy version

- .github/workflows/nightly-test.yml
> [CI] fix nightly-test

- .github/workflows/buildwebsite.yml
- .github/workflows/unittests-gpu.yml
- .github/workflows/unittests.yml
- ci/batch/compile_notebooks.sh
- ci/batch/submit-job.py
- ci/docker/README.md
- ci/docker/devel_entrypoint.sh
- ci/docker/gluon_nlp_job.sh
- ci/docker/install/install_horovod.sh
- ci/docker/install/install_jupyter_lab.sh
- ci/docker/install/install_llvm.sh
- ci/docker/install/install_openmpi.sh
- ci/docker/install/install_python_packages.sh
- ci/docker/install/install_tvm_cpu.sh
- ci/docker/install/install_tvm_gpu.sh
- ci/docker/install/install_ubuntu18.04_core.sh
- ci/docker/start_jupyter.sh
- ci/docker/ubuntu18.04-cpu.Dockerfile
- ci/docker/ubuntu18.04-gpu.Dockerfile
- setup.py
- tests/unittest/test_models.py
- tests/unittest/test_sampled_logits.py
- tests/unittest/test_transforms.py
> [v0.10.x] Port ci from v0.x

- .pytype.cfg
- docs/examples/sentence_embedding/bert.md
- scripts/parsing/parser/biaffine_parser.py
Signed-off-by: Sheng Zha <zhasheng@amazon.com>
> Update docs (#1521)

- tools/batch/submit-job.py
- tools/docker/gluon_nlp_job.sh
Setup g4dn.4x job definition to use 2G shared memory
> [CI] Update docker

- docs/api/attention.rst
- docs/conf.py
- src/gluonnlp/attention_cell.py
Sphinx has upgraded to v4.0. This introduced some issues in website build. This PR will try to fix these issues. The alternative way is to freeze sphinx package to v3.5.4
> [CI] Fix website build

- docs/conf.py
Fix CI build issue for v0.x branch
> [v0.x] Upgrade sphinx

- docs/conf.py
Fix CI build issue for v0.10.x branch
> [v0.10.x] Upgrade sphinx

- tools/docker/gluon_nlp_job.sh
> [CI] fix gluon_nlp_job.sh
