dmlc/gluon-nlp

Jenkinsfile
Makefile
docs/api/model.rst
docs/conf.py
docs/index.rst
env/doc.yml
gluonnlp/data/word_embedding_evaluation.py
gluonnlp/embedding/evaluation.py
gluonnlp/embedding/token_embedding.py
gluonnlp/model/attention_cell.py
gluonnlp/vocab.py
scripts/beam_search/beam_search_generator.rst
scripts/language_model/word_language_model.rst
scripts/nmt/machine_translation.rst
scripts/sentiment_analysis/sentiment_analysis.rst
scripts/word_embedding_evaluation/extended_results.ipynb
scripts/word_embedding_evaluation/word_embedding_evaluation.rst
setup.py

This PR fixes all documentation that causes warnings when building the documentation. It also switches the CI to only pass if the documentation doesn't cause warnings.
The rationale is to make sure that we never create any errors in our documentation by accident (broken links, missing files, etc.).

Fix sphinx docs

---

Jenkinsfile
env/py2.yml
env/py3.yml
setup.py

This enables test parallelization to make use of all CPUs on our CI server and speed up our tests.

Enable test parallelization

---

contributor.rst
gluonnlp/data/conll.py
gluonnlp/data/language_model.py
gluonnlp/data/sentiment.py
gluonnlp/data/translation.py
gluonnlp/data/utils.py
gluonnlp/data/word_embedding_evaluation.py
gluonnlp/embedding/token_embedding.py

* add a function _get_home_dir() to obtain the directory for storing datasets/models/pre-trained word embeddings
* change the functions that specify os.path.join('~', '.mxnet', ...) and update the corresponding documentations
* correct documentation errors in some classes, e.g., BiggerAnalogyTestSet, YangPowersVerb130 and so on. 

add function _get_home_dir() and update documentations

---

env/doc.yml
env/py2.yml
env/py3.yml
env/pylint.yml
gluonnlp/model/attention_cell.py
scripts/nmt/encoder_decoder.py
scripts/nmt/translation.py

fix `__call__` to call the `__call__` of parent class, so that it will work with forward hook in gluon.

fix __call__ for blocks to allow hook

---

Jenkinsfile
env/py2.yml
env/py3.yml
setup.py

Revert "Enable test parallelism (#97)"
This reverts commit a00cd6f489ee2bec81dad1784b92e63770ac6843.
Race conditions are frequent. Let's disable this until the parallel test workers
tests are set up to use independent environments.

Revert "Enable test parallelism (#97)"

---

setup.py

specify nltk version due to incompatible change in nltk 3.3 http://www.nltk.org/news.html?highlight=moses#id1

specify nltk version

---

gluonnlp/data/language_model.py
tests/unittest/test_datasets.py

Gluon-NLP already includes the preprocessed word level WikiText datasets. Infrequent words are replaced by an `unk` token. The raw datasets before the addition of unk tokens are useful for character level work or for creating newly derived datasets.

WikiText raw character level datasets

---

docs/examples/language_model/language_model.ipynb

This adapts the notebook to the changes required after https://github.com/dmlc/gluon-nlp/pull/120 was merged.
For some reason performance drops, however using `last_batch='keep'` and setting a padding token did not help either.

Fix language_model.ipynb

---

gluonnlp/embedding/token_embedding.py
tests/unittest/test_vocab_embed.py

Expose token_to_idx as public attribute of TokenEmbedding class, just as it is exposed in Vocabulary

Expose Inverse Vocab via TokenEmbedding class as well

---

README.rst
docs/api/data.rst
docs/examples/language_model/language_model.ipynb
gluonnlp/__init__.py
gluonnlp/data/__init__.py
gluonnlp/data/batchify.py
gluonnlp/data/dataset.py
gluonnlp/data/language_model.py
scripts/language_model/word_language_model.py
tests/unittest/test_datasets.py
tests/unittest/test_models.py

Reverts dmlc/gluon-nlp#128
There is no consensus that usage of WikiText for non-LM purpose should be supported at the cost of making the LM API more complicated (by eg. making the `bptt_batchify` and `batchify` functions standalone).

Revert "Don't treat language model datasets special"

---

scripts/language_model/word_language_model.py

The loss logged didn't consider the number of contexts used for training, yielding extremely large ppl.

Fix word_language_model script for multi-gpu

---

docs/examples/word_embedding/word_embedding.ipynb

https://github.com/apache/incubator-mxnet/issues/11271
The behavior of nd.topk under the presence of `nan` values changed, causing wrong results in the pretrained word embeddings notebook due to `def norm_vecs_by_row(x)` inducing `nan` values for `0` word vectors. This PR adds a small epsilon to `def norm_vecs_by_row(x)` so that `nan` values are avoided.

Workaround mxnet nd.topk regression

---

gluonnlp/data/batchify.py
scripts/nmt/train_gnmt.py
scripts/nmt/train_transformer.py

Set the encoding to be UTF-8 in the NMT examples + Fix the docstring of batchify

Small bug fix + doc fix

---

scripts/word_embeddings/utils.py

When running `run_all.sh` got a bug:
```
context = [mx.gpu(int(i)) for i in args.gpu]
TypeError: 'int' object is not iterable
```
Could be worth adding `run_all.sh` to the CI. Also, could `results-vocablimit.csv` be added to the repository?

fix bug in utils.py

---

Jenkinsfile
gluonnlp/model/beam_search.py
gluonnlp/model/train/language_model.py
scripts/beam_search/beam_search_generator.py
tests/unittest/test_beam_search.py

The following run was broken.
`python beam_search_generator.py --bos I think --lm standard_lstm_lm_200`
This PR fixes the issue by adding state_info to language model while preserving existing behaviors.

fix beam search script

---

gluonnlp/embedding/token_embedding.py

Currently `TokenEmbedding.from_file` crashes if it the input file has an inconsistent encoding (i.e. not all words can be encoded in the given encoding - usually UTF-8). With this PR, the invalid lines are skipped.
The error can only occur if the input file is invalid. However sometimes users cannot control the input file. An example file is https://s3-us-west-1.amazonaws.com/fasttext-vectors/word-vectors-v2/cc.ko.300.vec.gz which contains inconsistent encodings.

TokenEmbedding: Skip lines with invalid bytes instead of crashing

---

Jenkinsfile

Previously the exit status of codecov.sh was returned in the PY3 tests, causing them to pass as long as the code coverage report was successfully submitted. This is of course not what we want.

Return py.test exit status even when running codecov.sh

---

gluonnlp/embedding/token_embedding.py
tests/unittest/test_datasets.py

Sometimes users may input faulty embeddings that contain very long words (eg. a word with 50k characters as in https://s3-us-west-1.amazonaws.com/fasttext-vectors/word-vectors-v2/cc.ky.300.vec.gz ).
This should lead to no user-visible changes.

Use object dtype when serializing TokenEmbedding.idx_to_token

---

gluonnlp/data/word_embedding_evaluation.py
tests/unittest/test_datasets.py
tests/unittest/test_vocab_embed.py

The segments in WordSim353 are overlapping, so the `nlp.dataset.create('WordSim353', segment='all')` contained duplicates.

Remove duplicates in WordSim353 when combining segments

---

gluonnlp/model/convolutional_encoder.py
tests/unittest/test_convolutional_encoder.py

This makes ConvolutionalEncoder a HybridBlock. It also adds a few more test cases.
- If the nlp.model.ConvolutionalEncoder is hybridized, and the first forward pass runs with/without passing a mask, subsequent passes must follow the same convention as otherwise the symbolic graph doesn't match. Users can create two instances of nlp.model.ConvolutionalEncoder with shared parameters if they require both masked and unmasked inputs at the same time. If the nlp.model.ConvolutionalEncoder is not hybridized there are no changes to the current behavior. However users may have a .hybridize() statement in their code which was a no-op currently and will take effect if this PR is merged.

Hybridize convolutional encoder

---

Jenkinsfile

Once the CI runs stable the debug statements should be removed.

Remove debugging printenv from Jenkinsfile

---

Jenkinsfile
README.rst

Currently the Readme does not render properly on Pypi. This attempts to fix the rendering by addressing the issues raised by `python setup.py check --restructuredtext --strict`.

Fix Readme formatting

---

env/py2.yml
env/py3.yml
setup.py
tests/unittest/train/test_embedding.py

After pytest-datadir was upgraded, Py2 CI starts failing as it does not find the addon anymore. This removes the addon and replaces it by some `os.path.realpath(__file__)` logic.
- Fix CI

Remove pytest-datadir

---

gluonnlp/base.py
tests/unittest/test_datasets.py

Follows the Python porting best practice [use feature detection instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection).

Use feature detection instead of version detection

---

gluonnlp/base.py
gluonnlp/model/train/embedding.py
gluonnlp/vocab/subwords.py
scripts/word_embeddings/evaluate_pretrained.py
scripts/word_embeddings/train_fasttext.py
scripts/word_embeddings/word_embeddings.rst
tests/unittest/test_vocab_embed.py
tests/unittest/train/test_embedding.py

This PR switches the internal implementation of `NGramHashes` to make use of just in time compiling if numba is available. The speed-up is around 30x in case of the `scripts/word_embeddings/train_fasttext.py` example (during the startup/preprocessing phase). If numba the speed of the new implementation is more or less equivalent.
- This breaks the API of NGramHashes in that now lists instead of NDArrays are returned. This is necessary as in mxnet empty NDArrays are disallowed / discouraged, but NGramHashes has previously returned empty NDArrays..
- This breaks the API of NGramHashes by removing the option to cache results, which is not helpful anymore.
- Since numba 0.39 (which was released a week ago), now lists of refcounted objects can be passed to numba optimized functions. This …

Speed up ngram hashing function with numba

---

gluonnlp/data/candidate_sampler.py
tests/unittest/test_candidate_sampler.py

This fixes `UnigramCandidateSampler`.
- `dtype='float64'` seems sufficient to avoid numerical issues (meaning out of range samples) for up to [0, 9M]. With float32 for values as small as 100k numerical issues would result in frequently sampling a value that is one too high. Due to https://github.com/apache/incubator-mxnet/issues/11551 this would go unnoticed and just sometimes lead to obscure crashes depending on the memory value read at the out of bound location.
- Also high should be == N, not N+1.

Fix UnigramCandidateSampler

---

gluonnlp/data/sampler.py
tests/unittest/test_sampler.py

``` python
list(nlp.data.FixedBucketSampler(
np.arange(16, 32), 8, num_buckets=2
bucket_scheme=nlp.data.ConstWidthBucket()))
```
Should result in exactly two batches of batch_size 8:
``` python
[[8, 9, 10, 11, 12, 13, 14, 15], [0, 1, 2, 3, 4, 5, 6, 7]]
```
Without this change, 3 batches with batch_size varying between 1, 7 and 8 are
generated.
@szhengac please let me know if this has any negative impact on your use-case.

Fix off by one error for ConstWidthBucket

---

scripts/nmt/transformer.py

Default values do not divide into the number of units (i.e., num_heads=5 doesn't divide into units=512).

Fixed default values of num_heads

---

gluonnlp/embedding/token_embedding.py

We currently distribute some pre-trained embeddings on with pre-initialized unknown token. This is known and a workaround has been implemented. Currently the workaround treats the unknown token and vector loaded from the npz file as correct, even if the user specifies a special initialization function, instead of re-initializing it.
The reasoning was, that for some embeddings the unknown token vector in the npz file may actually be valuable and shouldn't be overwritten. However, this was not a good default behavior. With this PR, the unknown vector from the npz will only be preserved if `init_unknown_vec=None`.
Note this only affects embeddings distributed by us on S3.
Thanks @garima3292 for reporting this issue.

Re-initialize the unknown token vector for npz distributed on S3 by default

---

env/doc.yml
env/py2.yml
env/py3.yml
gluonnlp/data/word_embedding_evaluation.py

The problematic server now servers a valid SSL certificate. Also https://github.com/apache/incubator-mxnet/pull/11546 will add the option upstream.

Remove gluon.utils.download copy with verify_ssl support

---

docs/examples/language_model/language_model.ipynb
gluonnlp/data/__init__.py
gluonnlp/model/__init__.py
gluonnlp/model/train/__init__.py
gluonnlp/model/train/language_model.py
gluonnlp/vocab/__init__.py

The previous import structure was prone to cyclical imports and in some cases would error out with `undefined variable X` on doing `from .X import *; __all__= (X.__all__)`. Also, sometimes package internal imports were `from gluonnlp.X import Y`, where they should have used a relative module internal path. The PR also sorts the changed imports alphabetically.
This also follows the common practice described in http://platanios.org/assets/pdf/teaching/writing_python_libraries.pdf

Improve imports structure

---

docs/api/data.batchify.rst
gluonnlp/data/batchify.py

batchify.Pad currently allocates a large NDArray of the final shape, then converts all to be Padded datastructures to mx.nd.NDArray and then writes each axis of the large NDArray with the to be Padded array (thereby padding it). This is highly undesirable as repeatedly writing to the different axes of the NDArray is very expensive. This PR changes the internal implementation to convert everything to numpy instead which results in a 50x Speedup (even when the input is a list of ndarrays).
This leads to a 50 times speed up for all supported input datastructures (nested python lists, numpy arrays, ndarrays) according to the following benchmark script:
```
import mxnet as mx
import random
import numpy as np
import gluonnlp as nlp
random.seed(1)
p = nlp.data.batchify.Pad()
l = [[1] * …
```

Speed up batchify.Pad

---

docs/api/data.rst
docs/examples/language_model/language_model.ipynb
env/doc.yml
env/py2.yml
env/py3.yml
gluonnlp/data/transforms.py
scripts/nmt/train_transformer.py
setup.py
tests/unittest/test_transforms.py

nltk has deprecated its moses port due to LGPL 2.1+, and they have creates a new library called [sacremoses](https://github.com/alvations/sacremoses). This pr add dependency on sacremoses.

Add sacremoses

---

gluonnlp/data/dataset.py
tests/unittest/test_datasets.py

In the current `LanguageModelDataset.bptt_batchify`, elements of the "last batch" (defined as the extra words at the end of the dataset: `data[(len(data) // batch_size) * batch_size:]`) would incorrectly be split evenly among all rows in the batch dimension. However, each row in our batches should contain a independent context. The correct context for the words in the "last batch" is only the very last row. This PR fixes the logic and adds tests.

Fix LanguageModelDataset.bptt_batchify

---

gluonnlp/data/transforms.py
tests/unittest/test_datasets.py

The sacremoses can be imported using python2, but the instantiation of the mose  tokenizer/detokenizer can cause error. This pr fixes this issue. 

Fix error of instantiation of MosesTokenizer and MosesDetokenizer using Python2

---

gluonnlp/data/batchify.py

See https://github.com/dmlc/gluon-nlp/pull/249#issuecomment-409807866

Warn only once about use of mx.nd.NDArray in Pad()

---

gluonnlp/data/stream.py
scripts/language_model/large_word_language_model.py

This makes DataStream.transform() conform to the behavior of upstream DataSet.transform().
- @eric-haibin-lin

 Fix API discrepancy between upstream Dataset.transform() and GluonNLP DataStream.transform()

---

gluonnlp/model/train/embedding.py
gluonnlp/vocab/subwords.py
scripts/word_embeddings/evaluate_pretrained.py

This improves the behavior of the fastText embedding models under edge cases. Now KeyError is raised instead of AssertionError when the model does not support imputing an embedding for an unknown word. (This may happen when the model only contains large n-grams such as 5-grams and the unknown word is too short). Further, the end of sentence token was not set correctly before due to a typo.

Fixes for embedding training models

---

docs/api/data.rst
gluonnlp/data/dataset.py
gluonnlp/data/stream.py
gluonnlp/data/utils.py
tests/unittest/test_datasets.py

See Changes below. This was part of https://github.com/dmlc/gluon-nlp/pull/218. I split up the PR to make it easier to review / discuss.
- Remove option to iterate over a list of Streams. This allows keeping the implementation simple. A list of streams can be transformed into a single stream using `zip`.
- Add option to use multi-processing (with a single worker process)
- An iterator over single sentences can still be obtained via `itertools.chain.from_iterable(corpus_stream)`. However, it can be useful to iterate over bigger chunks in the stream to speed up other steps in the data pipeline.
- Remove the `sampler` argument. It is not needed anymore. (Note that it still kept for LanguageModelStream, which internally now uses `itertools.chain.from_iterable(corpus_stream)`)
- Set the …

Refactor DataStream

---

scripts/tests/test_scripts.py
tests/unittest/train/test_dataloader.py

Test seems to cause deadlocks. See https://github.com/dmlc/gluon-nlp/issues/274
@szhengac

Disable test_sharded_dataloader

---

scripts/word_embeddings/evaluate_pretrained.py
scripts/word_embeddings/train_fasttext.py

Workaround missing makedirs(path, exist_ok=True)

Workaround missing makedirs(path, exist_ok=True)

---

docs/api/model.rst
gluonnlp/model/sampled_block.py
gluonnlp/model/train/language_model.py
tests/unittest/test_models.py
tests/unittest/test_sampled_logits.py

- NCELogits is usually used together with SigmoidBCELoss. This PR update the output of NCELogits to be probably distribution ([1, 0, 0, .... 0]) instead of target class. This way the output can be fed into the loss directly. 
- Rename NCELogits/ISLogits to NCEDense/ISDense, since the output of these blocks are unnormalized predictions rather than log probabilities. Otherwise it's misleading to users

Make NCELogits easier to use, and rename XXLogits to XXDense

---

README.rst

fix relative links that pypi doesn't handle. See https://stackoverflow.com/questions/16367770/my-rst-readme-is-not-formatted-on-pypi-python-org
resolves #205

fix relative links that pypi doesn't handle

---

gluonnlp/embedding/token_embedding.py

For some pretrained embeddings no subword / binary / ngram models were published
and trying to load them will fail. Currently "Cannot find pre-trained source X
for token embedding fasttext" will be raised, which is wrong given that the
source exists but simply no subword features are available for that source. Now
"No ngrams are available for {}." will be raised instead.
@eric-haibin-lin @szha we may want to do a patch release on Tuesday if we find more small usability issues like this

Improve error message when loading pretrained fasttext with ngrams

---

Jenkinsfile
Makefile
env/doc.yml
env/py2.yml
env/py3.yml
env/pylint.yml
examples

- force install in CI
- print xargs commands
- fix pandoc version, since the utils.pandoc in nbconvert (dep of nbsphinx) has max version of 2.0.0 https://github.com/jupyter/nbconvert/blob/master/nbconvert/utils/pandoc.py#L18

make CI more debug-friendly

---

conftest.py
tests/unittest/batchify/test_batchify_language_model.py
tests/unittest/conftest.py
tests/unittest/test_models.py
tests/unittest/test_stream.py

This adds session scope fixtures for the WikiText2 dataset throughout the test suite. Consequently dataset is read only once.

Session scope fixtures for WikiText2

---

gluonnlp/base.py
scripts/tests/test_scripts.py
scripts/word_embeddings/train_fasttext.py
tests/unittest/test_datasets.py

Enable word embedding scripts tests

---

env/doc.yml

fix pandoc warning
```
RuntimeWarning: You are using an unsupported version of pandoc (2.0.0.1).
Your version must be at least (1.12.1) but less than (2.0.0).
Refer to http://pandoc.org/installing.html.
```

fix pandoc warning

---

.gitignore
gluonnlp/data/corpora/large_text_compression_benchmark.py

gluonnlp.data.Text8(segment='train') was not working when I tried to follow the tutorial. It turned out that archive name for text8 in large_text_compression_benchmark.py was wrong. Hence, I changed the archive name.

Correct text8 file name in corpora

---

docs/examples/word_embedding/word_embedding_training.md
scripts/tests/test_scripts.py
scripts/word_embeddings/data.py
scripts/word_embeddings/evaluate_pretrained.py
scripts/word_embeddings/evaluation.py
scripts/word_embeddings/index.rst
scripts/word_embeddings/train_sg_cbow.py
src/gluonnlp/data/batchify/embedding.py
tests/unittest/batchify/test_batchify_embedding.py

This adds support for arbitrary dtype to EmbeddingCenterContextBatchify. Also some refactoring of the `data.py` in the word embedding scripts folder is done. Further `train_fasttext.py` is renamed to `train_sg_cbow.py` to better reflect it's scope.
As NDArray does not support arbitrary dtype (e.g. string / python object), the returned types of EmbeddingCenterContextBatchify are changed to numpy arrays.
Todo: Update example notebook for changed `data.py`

Add dtype support to EmbeddingCenterContextBatchify

---

scripts/question_answering/attention_flow.py
scripts/question_answering/bidaf.py
scripts/question_answering/data_processing.py
scripts/question_answering/official_squad_eval_script.py
scripts/question_answering/performance_evaluator.py
scripts/question_answering/question_answering.py
scripts/question_answering/question_id_mapper.py
scripts/question_answering/similarity_function.py
scripts/question_answering/tokenizer.py
scripts/question_answering/train_question_answering.py
scripts/question_answering/utils.py
scripts/tests/test_question_answering.py
src/gluonnlp/data/question_answering.py

Add Bidirectional Attention Flow model from [the original paper](https://arxiv.org/pdf/1611.01603.pdf). Current implementation achieves similar results with hyperparameters taken from the paper (for exact values look `get_args()` method in `train_question_answering.py`) on a single gpu: EM=67.1 and F1=76.9. This implementation also supports multigpu.
Default arguments of the code match to hyperparameters of the paper. One can run the training script in 3 different modes: data preprocessing, training, evaluation (last two can be combined). If data preprocessing step hasn't been done before running training, the data would be automatically preprocessed. For common usage, the following command line is enough (run from gluon-nlp root folder):
```
python3 -m …
```

Add BiDAF question answering model

---

scripts/machine_translation/dataprocessor.py
src/gluonnlp/data/dataloader.py
tests/unittest/train/test_dataloader.py

Update SharededDataLoader according to https://github.com/apache/incubator-mxnet/pull/13447

[Feature] update sharded loader

---

src/gluonnlp/model/bert.py

https://github.com/apache/incubator-mxnet/pull/13732
There was a typo in the `nn.LayerNorm` documentation. It turns out that we can safely reuse `nn.LayerNorm` which is faster than the implementation in GluonNLP. 
As a sanity check, I run `compare_tf_gluon_model.py` again with `bert_24_1024_16/bert_12_768_12` on `book_corpus_wiki_en_uncased/book_corpus_wiki_en_cased` and the test passes. 
@fierceX @haven-jeon

[FIX] Update BERTLayerNorm Implementation

---

scripts/bert/compare_tf_gluon_model.py
scripts/bert/dataset.py
scripts/bert/finetune_classifier.py
scripts/bert/index.rst
src/gluonnlp/model/bert.py
src/gluonnlp/optimizer/__init__.py
src/gluonnlp/optimizer/bert_adam.py

- update command with adamw optimizer, which applies weight decay instead of l2 loss with Adam, as is used in the original TF bert repo.  (requires https://github.com/apache/incubator-mxnet/pull/13728)
- update training script with option for gradient accumulation for bert_large model
- update training script to use bucket sampler, which speeds up training by 2x
Other ongoing BERT efforts may also benefit from this PR @fierceX @kenjewu @haven-jeon 

[SCRIPT] Improve BERT fine-tuning script with AdamW optimizer, bucketing and gradient accumulation

---

src/gluonnlp/data/sampler.py
tests/unittest/test_sampler.py

Added a split sampler for distributed training with multiple nodes. Each node initializes the sampler with total number of nodes (num_parts) and its rank (part_idx) in the cluster, and samples dataset randomly from that partition. This can be used as a custom sampler with SimpleDatasetStream for a list of files, where each split is a subset of all files. 
#478 

[Feature] Add split sampler for distributed training

---

scripts/text_classification/fasttext_word_ngram.py

Small update to remove unused argument
In fasttext_word_ngram.py batch_size is used but batch-size is never used

[BUGFIX] Remove unused argument in fasttext_word_ngram.py

---

scripts/bert/index.rst
src/gluonnlp/optimizer/bert_adam.py
tests/unittest/test_optimizer.py

The Adam optimizer in the official BERT repository does not have the bias correction term in Adam. However, this was added in the initial PR for BERTAdam. 
Now I am removing it to make the optimizer consistent with the official implementation. 
The goal is to make the reproduction of other fine-tuning tasks easier (with hyper-parameters mentioned in the BERT official repo/paper). 
Unfortunately other ongoing BERT efforts may be affected @fierceX @haven-jeon  #493 #481

[FIX] Remove bias correction term in BERTAdam

---

src/gluonnlp/utils/parameter.py
tests/unittest/test_utils.py

fix parameter clip where it causes error such as
> Parameter 'gnmt_enc_rnn0_l_i2h_weight' was not initialized on context cpu(0). It was only initialized on [gpu(0), gpu(1), gpu(2), gpu(3)]

[BUGFIX] fix parameter clip

---

scripts/bert/compare_tf_gluon_model.py

I didn't intend to check in this code to GluonNLP. It was added during local testing. Reverting. 

[FIX] Revert an unintended change

---

scripts/tests/test_scripts.py
scripts/word_embeddings/evaluate_pretrained.py
scripts/word_embeddings/evaluation.py
src/gluonnlp/embedding/token_embedding.py
src/gluonnlp/vocab/vocab.py
tests/unittest/test_vocab_embed.py

Previously, if `TokenEmbedding.unknown_lookup` was set, it was always used, even for words that could not be inferred by `unknown_lookup`. This would raise `KeyError`. But, if TokenEmbedding.unknown_token exists, the unknown vector should be returned. Tests are added.

[API] Better handle case when backoff is not possible in TokenEmbedding

---

src/gluonnlp/model/parameter.py
tests/unittest/test_models.py

Fix the problem where the weight dropped parameter didn't copy data/grad from original parameter. Fix flaky test. Previously WeightDropParameter has only been used for fresh training and didn't test the case where existing parameter needs to be copied.
- It doesn't change the behavior of weight drop for previous use case, which always starts a fresh copy.

[BUGFIX] Fix Weight Drop and Test

---

src/gluonnlp/embedding/token_embedding.py

Fix docstring for TokenEmbedding

[DOC] Fix docstring for TokenEmbedding

---

src/gluonnlp/model/transformer.py

Change the default value of flag use_layer_norm_before_dropout to false. Otherwise, the training of transformer model will diverge with the default cmd.

[FIX] Fix divergence of the training of transformer

---

scripts/machine_translation/dataprocessor.py

Fix the following error: 
```
File "~/machine_translation/dataprocessor.py", line 268, in write_sentences
of.write(sent + '\n')
TypeError: must be unicode, not str
```

Use unicode instead of string for writing files

---

README.rst

This PR changes the MXNet dependency to the last stable MXNet release 1.3.1 instead of nightly builds.
- Change GluonNLP MXNet dependency

[BUGFIX] Fix GluonNLP MXNet dependency

---

src/gluonnlp/initializer/initializer.py
tests/unittest/test_initializer.py

BERT requires TruncNorm initializer. This code uses scipy to draw samples from distribution as a quick solution. If it would be too slow for bigger sample sizes, will have to rewrite it.

[Feature] Add TruncNorm initializer for BERT

---

scripts/natural_language_inference/index.rst
scripts/natural_language_inference/main.py

Use glove.840B.300d instead of glove.6B.300d. Updated accuracy numbers.

[BUGFIX] use glove.840B.300d for NLI experiments

---

src/gluonnlp/data/sampler.py

[DOC] Update documentation for SplitSampler

---

src/gluonnlp/data/word_embedding_evaluation.py

As described in https://github.com/dmlc/gluon-nlp/issues/405 many auto-downloaded datasets doesn't provide any data sample. It is not clear what samples look like and if any pre-processing is done. This PR adds an example to the MEN data by showing the number of samples in the test set and the first sample in the dataset. I suggest we follow this style and enhance the remaining datasets. 
Note that I deliberately specified `root=xxx` to make sure the data is downloaded each time doctest runs on CI, and `-etc-` makes any string message (including msg for downloading dataset) is acceptable. 

[DOC] MEN dataset documentation enhancement

---

src/gluonnlp/optimizer/bert_adam.py

This PR updates the default value for eps in the BERTAdam optimizer, so that it is consistent with the official bert repo. Note that a few other fine-tuning scripts are also using this optimizer. The epsilon values in these scripts are all explicitly provided in these scripts and will not be affected. #571 by @kenjewu  #493 by @fierceX  and https://github.com/dmlc/gluon-nlp/blob/master/scripts/bert/finetune_classifier.py by @haven-jeon. @bikestra your ongoing BERT+NER work might be affected. 

[FIX] Update default value of BERTAdam epsilon to 1e-6

---

scripts/bert/index.rst

Add sst-2 result to the website. 

[Script] Add BERT SST-2 finetuning result

---

README.rst
docs/api/modules/data.rst
docs/index.rst
scripts/bert/index.rst
src/gluonnlp/data/corpora/wikitext.py

[DOC] Update Readme with correct mxnet version

---

scripts/bert/create_pretraining_data.py

Fix multiprocessing bug which causes unnecessary dispatching to single worker.
I guess the other condition branch is intended for serial execution, while it will never be triggered when `nworker` is 1.

[BUGFIX] Fix multiprocessing bug in create_pretraining_data.py for bert

---

scripts/bert/create_pretraining_data.py
scripts/bert/run_pretraining.py

This PR uses np.savez_compressed API to reduce the size of the produced npz files. In general it reduces the storage by 75%. 
This leads to longer loading time for the npz file. On this, adding `PrefetchingStream` hides the loading latency pretty well. 

[BERT] Generate BERT training samples in compressed format

---

scripts/bert/embedding.py
scripts/bert/run_pretraining.py
scripts/tests/test_bert_embedding.py

Fix some bugs and add small features to the BERT pretraining and embedding scripts. Summary below:
For `scripts/bert/run_pretraining.py`:
* [FEATURE] The script can load and fine-tune any BERT model, not just BERT base.
* [FEATURE] Add command-line option to only run the eval.
* [BUGFIX] In `evaluate()`, move the total loss calculation outside of checkpointing. If the logging interval is larger than the number of data batches, the total losses would be 0.
* [BUGFIX] Loading would fail when loading a model a model that has already been fine-tuned with float16 (e.g. from a previous checkpoint). Add a `model.cast()` before attepting to load a checkpoint.
* Add some extra comments and logging.
For `scripts/bert/embedding.py`:
* [BUGFIX] Do not lowercase the input data if loading a cased BERT …

[BUGFIX][FEATURE] Fixes for BERT embedding, pretraining scripts

---

src/gluonnlp/model/bert.py

fix code comment

---

src/gluonnlp/data/utils.py
tests/unittest/test_bertvocab.py

Fix the bug mentioned in #652 . `wiki_cn_cased` vocab and `wiki_multilingual_cased` vocab have been converted. Now update the hash code of the relevant vocab.

[BUGFIX] Update hash of wiki_cn_cased and wiki_multilingual_cased vocab

---

docs/examples/sentence_embedding/bert.md

attempt to mitigate issue #666 

[DOC] Add alternative link for bert scripts

---

src/gluonnlp/data/utils.py
src/gluonnlp/model/bert.py

[DOC]fix comment of train_valid_split

---

src/gluonnlp/utils/parameter.py

fix #579 by adding warning about trainer.step usage.

[DOC] fix #579

---

README.rst

This fixes `nlp.data.WikiText2(segment='train')[0][0:5]` to `nlp.data.WikiText2(segment='train')[0:5]` because `nlp.data.WikiText2(segment='train')[0][0:5]` is '='.

[TUTORIAL] Fix README WikiText2 example

---

scripts/bert/convert_tf_model.py

fix bert forward call parameter mismatch in scripts/bert/convert_tf_model.py line 154
- fix error below:
Traceback (most recent call last):
File "/data/etb/data1/NLP/Program/bert/gluon_nlp_fork/scripts/bert/convert_tf_model.py", line 154, in <module>
out = bert(ones, ones, mx.nd.array([1, 2])) 
File "/data/etb/miniconda3/envs/mxnet_py3/lib/python3.6/site-packages/mxnet/gluon/block.py", line 540, in __call__
out = self.forward(*args)
File "/data/etb/miniconda3/envs/mxnet_py3/lib/python3.6/site-packages/gluonnlp/model/bert.py", line 435, in forward
'masked_positions tensor is required for decoding masked language model'
AssertionError: masked_positions tensor is required for decoding masked language model

[FIX] fix bert forward call parameter mismatch in convert_tf_model.py

---

scripts/bert/index.rst
scripts/bert/staticbert/static_export_base.py
scripts/tests/test_scripts.py

This will export the base BERT model for use with the MXNet Module API.
It was adapted from the `static_export_squad.py`
Use cases can include fine tuning for Clojure and Scala APIs. 
* Have used it successfully to reproduce https://gluon-nlp.mxnet.io/examples/sentence_embedding/bert.html in Clojure - PR in MXNet will be coming shortly
Python is not my usual language - so feedback is welcome :)

[SCRIPT] - Add static BERT base export script (for use with MXNet Module API)

---

scripts/bert/pretraining_utils.py

`total_mlm_loss` was only updated every `log_interval` steps, and losses of last few steps are not added to the total loss. This PR fixes that.
@khetan2 @paperplanet @AI-richard FYI

[BUGFIX] Fix mlm_loss reporting for eval dataset

---

docs/examples/sentence_embedding/bert.md

http://ci.mxnet.io/blue/organizations/jenkins/GluonNLP-py3-master-gpu-doc/detail/PR-648/1/pipeline shows that the BERT tutorial cannot run with the bash command. It's still not clear why it happens to me. This PR tries to replace bash with python code. 

[DOC] avoid using bash in BERT tutorial

---

scripts/bert/dataset.py

Fix the index for the MRPC test set. @pengxin99 

[BUGFIX] Fix mrpc dataset idx

---

scripts/bert/dataset.py
scripts/bert/finetune_classifier.py
scripts/bert/index.rst

[Enhancement] only use the best model for inference for bert classification

---

scripts/bert/pretraining_utils.py
scripts/bert/run_pretraining_hvd.py

[Enhancement] run evaluation periodically for BERT pre-training

---

conftest.py
env/cpu/py2.yml
env/cpu/py3-master.yml
env/cpu/py3.yml
env/gpu/py2.yml
env/gpu/py3-master.yml
env/gpu/py3.yml
setup.py

Should fix pytest > 4 support. See https://github.com/dmlc/gluon-nlp/issues/727

Pytest 4 support

---

README.rst

fix codes `nlp.Vocab(counter=nlp.data.Counter(train[0]))` to `nlp.Vocab(counter=nlp.data.Counter(train))`, because `train[0]` is '='.

[TUTORIAL] Fix vocab construction code in README

---

docs/api/modules/model.rst
src/gluonnlp/model/__init__.py

http://gluon-nlp.mxnet.io/api/modules/model.html currently does not
differentiate pre-defined models exposed by the `get_model` function and other
components. This PR is a quick attempt to improve the distinction.
Further, `get_model` used a hardcoded `dataset=wikitext-2` argument. This is
likely by accident as the `get_model` function was initially mainly used for
language models, but now also provides access to other models such as Bert, for
which hardcoded dataset argument does not make sense.
For example, loading a Bert model with a prespecified Vocab currently requires doing
nlp.model.get_model('bert_12_768_12', dataset_name=None, vocab=vocabulary, ...)
instead of
nlp.model.get_model('bert_12_768_12', vocab=vocabulary, ...)
The latter version currently fails, as it will pass the …

[BUGFIX] [DOC] Update nlp.model.get_model documentation and get_model API

---

conftest.py

`request.node.rep_call` is only present if the setup succeeded. Thus test for
`request.node.rep_setup.failed` before accessing `request.node.rep_call`.
This improves error messages during test development (ie. when running pytest
with a wrong test). Without this change, tests will fail with `AttributeError: 'Function' object has no attribute 'rep_call'`

Fix conftest.py function_scope_seed

---

src/gluonnlp/vocab/vocab.py
tests/unittest/test_vocab_embed.py

Example use case in scripts/tests/test_dataprocessor.py where `eos_token ==
padding_token`. Prior to this fix, `eos_token == padding_token` lead to a
corrupted vocabulary index.
Example of the corrupted index:
> v = nlp.Vocab(...)
> v.idx_to_token
['<unk>', '<eos>', '<eos>', 'c', 'b', 'a']
> v.token_to_idx
{'<unk>': 0, '<eos>': 2, 'c': 3, 'b': 4, 'a': 5}
- This fix does not impact backward compatibility in that previously serialized
vocabularies will be restored exactly as serialized.
- Newly created vocabularies may differ, if up until now their index was corrupt
- The changes to the deserialization process in
https://github.com/dmlc/gluon-nlp/pull/732 and resulting execution of sanity
checks during deserialization would prevent deserialization of vocabularies
with a corrupt index. I …

[BUGFIX] Fix handling of duplicate special tokens in Vocabulary

---

docs/api/modules/index.rst
docs/api/modules/optimizer.rst
src/gluonnlp/optimizer/__init__.py
src/gluonnlp/optimizer/lamb.py
tests/unittest/test_lamb.py

The LAMB optimizer: 
It has been proposed in [Reducing BERT Pre-Training Time from 3 Days to 76 Minutes](https://arxiv.org/abs/1904.00962).
A simple neural network has been used for verification, and the results show that the model can converge normally with large batchsize. Need to be verified further on the BERT.
@eric-haibin-lin  Verification may require your help because of some computing resource limitations.

[FEATURE] Add LAMB optimizer

---

src/gluonnlp/data/batchify/batchify.py

padding value warning for `batchify.Pad()` if `padding_value` is 0. resolves #679

[DOC] batchify.Pad() padding value warning

---

scripts/bert/utils.py
setup.py
src/gluonnlp/_constants.py
src/gluonnlp/base.py
src/gluonnlp/embedding/token_embedding.py
src/gluonnlp/vocab/bert.py
src/gluonnlp/vocab/vocab.py
tests/data/vocab/backward_compat_0_7_corrupted_index
tests/unittest/corpora/test_wikitext.py
tests/unittest/test_bertvocab.py
tests/unittest/test_vocab_embed.py

Currently the `gluonnlp.Vocab` always assigns 0 as id of `<unk>` (#393). Further
reserved tokens are not exposed as attributes of the vocab (#572). This PR
addresses both issues.
optionally specify the index to be associated to a token for a subset of
tokens in the vocabulary. (Fixes #393)
optionally specify a Mapping, specifying identifiers for tokens that will be
exposed as attributes of the vocabulary (Fixes #572)
- The `token_to_idx` argument can only contain tokens that will actually be part
of the vocabulary. On the one hand, a user may not know which tokens will be
part of the vocabulary, eg. when specifying a maximum size argument. On the
other hand, if the user does not know if a certain token will be part of the
vocab or not, it seems unlikely that the user would like to …

[FEATURE] Flexible vocabulary

---

ci/jenkins/build_steps.groovy
docs/community/contribute.rst
docs/index.rst

contribute.rst currently contains invalid links. As CI checks links, this broke
all CI runs on the master branch. This should have broken all CI runs, including
pull-requests, but somehow didn't. This is tracked in #751.

[CI] Fix links in contribute.rst

---

env/cpu/py2.yml
env/cpu/py3-master.yml
env/cpu/py3.yml
env/gpu/py2.yml
env/gpu/py3-master.yml
env/gpu/py3.yml

After enabling linkcheck again in #752, it turns out that on the master branch linkcheck continues to fail due to issues with our the symbolic link to the model_zoo. There have been a number of bugfixes for sphinx linkcheck in recent versions. Thus let's update the version first before investigating the current continued failure.
Also, nbconvert 5.5 now supports pandoc 2.

[CI] Update CI dependencies

---

ci/jenkins/build_steps.groovy
docs/conf.py
src/gluonnlp/embedding/token_embedding.py
src/gluonnlp/vocab/vocab.py
tests/unittest/test_token_embedding.py
tests/unittest/test_vocab_embed.py

Prior to this commit, the TokenEmbedding constructor could only construct an
empty TokenEmbedding. However, an empty TokenEmbedding is of little use, thus
there exist a variety of places that modify and overwrite TokenEmbedding
internals after construction to "fill" the idx_to_token, idx_to_vec.
Examples are _load_embedding_text or _load_embedding_serialized.
This commits
1) makes these methods static and changes them to return the
idx_to_token and idx_to_vec,
2) extends the TokenEmbedding constructor to allow constructing a "non-empty"
TokenEmbedding given newly added idx_to_token and idx_to_vec arguments
This change is backwards compatible in that it does not change any public API
besides introducing idx_to_token and idx_to_vec arguments to TokenEmbedding. For
the future, the "empty" …

[REFACTOR] Refactor TokenEmbedding to reduce number of places that initialize internals

---

src/gluonnlp/embedding/token_embedding.py
tests/unittest/test_token_embedding.py

Follow-up on #750. #750 forgot to remove one leftover assertion, preventing serialization of TokenEmbedding with `emb[emb.unknown_token] != 0`.

[BUGFIX] Fix TokenEmbedding serialization with `emb[emb.unknown_token] != 0`

---

scripts/bert/finetune_classifier.py
scripts/bert/ner_utils.py
src/gluonnlp/model/bert.py

As title. Everything should go through `nlp.model.get_model`. @szha  @leezu 

[API] Remove get_bert_model from the public API list

---

docs/index.rst
docs/install.rst
env/cpu/py2.yml
env/cpu/py3.yml
env/gpu/py2.yml
env/gpu/py3.yml

update doc and CI to use mxnet 1.4.1

[DOC][CI] update to use mxnet 1.4.1

---

scripts/bert/finetune_classifier.py

Make test result.tsv consistent with the format required on GLUEBenchmark. 

[BUGFIX] Fix glue test result serialization

---

scripts/bert/data/classification.py
src/gluonnlp/data/glue.py
tests/unittest/test_datasets.py

Download the MRPC dataset hosted by the gluebenchmark.

[Dataset] Move MRPC dataset to API

---

scripts/tests/test_scripts.py
scripts/word_embeddings/evaluation.py
src/gluonnlp/data/word_embedding_evaluation.py
src/gluonnlp/model/bilm_encoder.py
tests/unittest/test_bilm_encoder.py
tests/unittest/test_bilmencoder.py
tests/unittest/test_datasets.py
tests/unittest/test_vocab_embed.py

Fix of initialization for the case of multiple levels in Bidirectional LM encoder. The problem was in passing `None` as an `input_size` to next layers for non-lstmpc cell types.

[BUGFIX] Fix init bug for multilevel BiLMEncoder

---

scripts/bert/data/baidu_ernie_data.py
scripts/bert/data/classification.py
scripts/bert/finetune_classifier.py
scripts/tests/test_scripts.py

add LCQMC, ChnSentiCorp dataset

[DATASET] add LCQMC, ChnSentiCorp dataset

---

ci/jenkins/Jenkinsfile_py3-master_gpu_doc

submit-job.py returns non-zero exit status if the AWS Batch Task fails. The AWS
Batch Task fails in case of the submitted "--command" returning non-zero exit
status. So far, in case of submit-job.py failing, the logs of "--command" were
not retrieved and potential problems were hard to debug.

[CI] Don't exit pipeline before displaying AWS Batch logfiles

---

README.rst

Fix broken badge icon in readme file.
Reference: https://github.com/dmlc/gluon-cv/pull/837

Fix badge icon

---

src/gluonnlp/data/sampler.py

[DOC] Fix code comment

---

Makefile
docs/api/modules/data.rst
src/gluonnlp/data/__init__.py
src/gluonnlp/data/glue.py
src/gluonnlp/data/intent_slot.py
tests/unittest/test_datasets.py

[DATASET] add atis and snips

---

docs/examples/sentence_embedding/bert.md

The "model" is a imported module from code section 1 and then overloaded on code section 4
```{.python}
model = model.classification.BERTClassifier(bert_base, num_classes=2, dropout=0.1)
```
This actually make this section not rerunable  and if anything need to call the module "model", it will call the BERTClassifier  object rather than the model imported in section 1. Propose to change the model to bert_classifier to avoid naming conflicts.

[DOC] change the variable model to bert_classifier

---

ci/jenkins/Jenkinsfile_py3-master_gpu_doc

Now that we have a 0.7x release branch, py3-master_gpu_doc must be extended to
support testing documentation on that branch. Previously only master branch and
pull requests were supported.

[CI] Support doc testing on arbitrary branches

---

src/gluonnlp/model/attention_cell.py

Remove a typo comma in `DotProductAttentionCell`'s docstring.
- Remove a typo comma in `DotProductAttentionCell`'s docstring.

[DOC] Fix a typo in attention_cell's docstring

---

ci/batch/submit-job.py

For example, "." is not allowed to occur in a jobName. As jobName is typically
based on branch name in our setup, "." may occur in the requested jobName
leading to failure. With this commit, all disallowed characters are simply
removed from the jobName.

Enforce AWS Batch jobName rules

---

README.rst

Remove Py2 icon from Readme. Add 3.7
Our CI does not test 3.7. Code may be broken on 3.7, though it's unlikely. I use 3.7 locally and haven't experienced problems.

[DOC] Remove Py2 icon from Readme. Add 3.7

---

scripts/bert/pretraining_utils.py
scripts/bert/run_pretraining.py
scripts/bert/run_pretraining_hvd.py

Fix Pad constructor to avoid printing warnings 

[Enhancement] Fix the usage of Pad in BERT

---

scripts/word_embeddings/model.py
scripts/word_embeddings/train_glove.py

Regression fixed by https://github.com/apache/incubator-mxnet/pull/15707

Remove temporary regression workarounds

---

ci/jenkins/build_steps.groovy
docs/api/modules/data.rst
docs/api/modules/optimizer.rst
docs/examples/machine_translation/gnmt.md
docs/examples/sentence_embedding/self_attentive_sentence_embedding.md
src/gluonnlp/data/corpora/wikitext.py

[DOC] fix broken links

---

scripts/bert/index.rst

[DOC] Fix wrong documentation for BERT custom vocab

---

docs/conf.py
env/cpu/py3-master.yml
env/cpu/py3.yml
env/docker/py3.yml
env/gpu/py3-master.yml
env/gpu/py3.yml
src/gluonnlp/vocab/vocab.py

This adds sphinx autodoc based on Python 3 typehints.
Impact: Auto-generate (missing) type annotations in the documentation based on machine-readable typehints. The auto-generated type annotations look as follows: http://gluon-nlp-staging.s3-accelerate.dualstack.amazonaws.com/PR-830/4/api/modules/vocab.html#gluonnlp.Vocab

Autodoc typehints

---

src/gluonnlp/data/batchify/language_model.py
tests/unittest/batchify/test_batchify_language_model.py

Remove incorrect vocab.padding_token requirement in CorpusBPTTBatchify.
This was not noticed before as `vocab[vocab.padding_token]` only fails if `vocab.padding_token is None and vocab.unknown_token is None`. It seems all experiments so far used an `unknown_token`.

[BUGFIX] Remove incorrect vocab.padding_token requirement in CorpusBPTTBatchify

---

src/gluonnlp/vocab/vocab.py
tests/unittest/test_models.py
tests/unittest/test_vocab_embed.py

https://github.com/dmlc/gluon-nlp/pull/732 forgot to remap the default specified in DefaultLookupDict, but only remapped the idx_to_token / token_to_idx data structures.
- Needs to be backported to 0.7

[BUGFIX] Fix Vocab with unknown_token remapped to != 0 via token_to_idx arg

---

env/cpu/py2.yml
env/cpu/py3-master.yml
env/cpu/py3.yml
env/docker/py3.yml
env/gpu/py2.yml
env/gpu/py3-master.yml
env/gpu/py3.yml
scripts/parsing/parser/biaffine_parser.py
scripts/parsing/parser/evaluate/evaluate.py
scripts/tests/test_scripts.py
src/gluonnlp/vocab/vocab.py
tests/unittest/test_models.py
tests/unittest/test_vocab_embed.py

Backport #862

---

docs/examples/machine_translation/transformer.md

`language.` is not tokenized correctly and causes mistranslation.

[DOC] Fix Machine Translation with Transformers example

---

src/gluonnlp/model/attention_cell.py

Otherwise it will throw an error "AttributeError: 'MultiHeadAttentionCell' object has no attribute '_query_units'" while training transformer.
@eric-haibin-lin 

fix broken multi-head attention cell

---

ci/jenkins/Jenkinsfile_py3-master_gpu_doc

In case a job times out, stdout.log and stderr.log files won't be uploaded to
S3.
Fixes https://github.com/dmlc/gluon-nlp/issues/881

Preserve stderr and stdout streams in doc CI stage for Cloudwatch

---

src/gluonnlp/vocab/subwords.py

This PR fixes a few documentation inconsistencies in package gluonnlp.vovab
- use the same parameter name in method signature and method documentation.
- explicitly document RuntimeException

[DOC] doc fix for vocab.subwords

---

scripts/word_embeddings/run_all.sh

Use the correct argument analog-max-vocab-size as indicated [here](https://github.com/dmlc/gluon-nlp/blob/master/scripts/word_embeddings/evaluate_pretrained.py#L66).

[BUGFIX] fix argument `analogy-max-vocab-size`

---

scripts/bert/bert_qa_evaluate.py

[BUGFIX] fix a SQUAD2.0 bug

---

scripts/bert/pretraining_utils.py
src/gluonnlp/data/batchify/batchify.py
tests/unittest/batchify/test_batchify.py

This PR adds an option to Pad batchify option to round the resulting size. It is especially important in FP16 training, like BERT training, as TensorCore algorithms may only be invoked when the sequence length is a multiple of 8.
@eric-haibin-lin FYI

[FEATURE] Padding seq length to multiple of 8 in BERT model

---

scripts/bert/index.rst
src/gluonnlp/model/bert.py

Cite source of pretrained parameters for bert_12_768_12 in docstring and on modelzoo.
Fixes #896
- Cite source of pretrained parameters for bert_12_768_12
- @eric-haibin-lin

[DOC] Cite source of pretrained parameters for bert_12_768_12

---

scripts/bert/finetune_classifier.py

Provide padding value during batchification. 

[Enhancement] remove padding warning in finetune script

---

src/gluonnlp/data/utils.py

Sometimes users have typos in their `dataset_name` argument for `model.get_model`. Report existing vocabularies when a vocab is not found. 

[DOC] Enhance error message when vocab is not found

---

src/gluonnlp/model/lstmpcellwithclip.py

Fix the math formula in docs for `gluonnlp.model.LSTMPCellWithClip`. There is an extra `}` that caused formula not displaying as expected. Attached with documentation website screenshot to show the problem.

[DOC] fix math formula in docs

---

setup.py

This PR implements "fail early at install time" principle to make sure user's don't install GluonNLP with an unsupported version of Python. As of version 9.0.1 pip will honour the `python_requires` string.
https://github.com/dmlc/gluon-nlp/pull/918 adds a runtime exception if GluonNLP is loaded with unsupported Python version.
https://python3statement.org/practicalities/

Declare Python version requirement in setup.py

---

docs/api/modules/index.rst
docs/api/modules/utils.rst
docs/conf.py

The website API doc does not include nlp.utils APIs. 

[DOC] Add missing docs for nlp.utils

---

src/gluonnlp/data/stream.py

Since default np.int_  is int32 for Windows, an upper limit for random seed of 2**32 rises a `ValueError: high is out of bounds for int32`.
with `np.iinfo(np.int_).max`, np.random.randint is platform-independent
- very small fix to allow Windows users to use module (otherwise random seed is bugged)

[BUGFIX] Corrected np.random.randint upper limit in data.stream.py

---

pytest.ini

Pytest raises warnings for undeclared markers.
pytest.warning_types.PytestUnknownMarkWarning: Unknown pytest.mark.seed - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
Warnings are treated as errors when running with `pytest -Werror`

[Tests] Declare pytest seed marker in pytest.ini

---

setup.py

numba<=0.45.1 is incompatible with numpy>=1.17

Update numba dependency in setup.py

---

scripts/machine_translation/index.rst
scripts/machine_translation/inference_transformer.py
scripts/tests/test_scripts.py

Make the following change to machine translation folder:
1. Add flag --gpu 0 to index.rst
2. change gpus to gpu as the script only allows evaluation on singe gpu.

[BUGFIX] Fix index.rst and gpu flag in machine translation

---

src/gluonnlp/data/batchify/embedding.py
tests/unittest/batchify/test_batchify_embedding.py

np.asarray([]) defaults to float32 dtype. Thus an input of [[1,2,3,...], []]
would yield returnvalue of float32 dtype instead of expected int64 dtype.

[BUGFIX] Make EmbeddingCenterContextBatchify returned dtype robust to empty sentences

---

docs/api/modules/data.rst
docs/examples/sentence_embedding/elmo_sentence_representation.md
setup.py
src/gluonnlp/data/transforms.py
tests/unittest/test_transforms.py

NLTKMosesTokenizer works only with unsupported / outdated nltk==3.2.5 but was
kept in GluonNLP as SacreMosesTokenizer does not support Python 2. Drop it as
Python 2 support has been dropped.
- By design this is backwards incompatible.

Remove NLTKMosesTokenizer in favor of SacreMosesTokenizer

---

ci/jenkins/Jenkinsfile_py3-master_cpu_unittest
ci/jenkins/Jenkinsfile_py3_cpu_unittest
conftest.py

See #944. CPU integration tests were previously not executed.

[CI] Enable integration tests on CPU

---

docs/api/modules/data.batchify.rst
scripts/tests/test_scripts.py
src/gluonnlp/data/batchify/batchify.py
tests/unittest/batchify/test_batchify.py

During the implementation, I find that sometimes we need to have the following functionality:
```python
for sample in data_loader:
foo(sample.data, sample.label)
```
Now, the feature is available via NamedTuple, we can combine NamedTuple and the other batchify functions.

[FEATURE] Add NamedTuple + Dict batchify

---

ci/batch/docker/gluon_nlp_job.sh

Set `-o pipefail` for gluon_nlp_job.sh
I'll have to rebuild the docker container after this change.

[CI] Correct propagation of error codes in GluonNLP-py3-master-gpu-doc

---

setup.py
src/gluonnlp/__init__.py
src/gluonnlp/vocab/vocab.py
tests/unittest/test_datasets.py

Deprecate specification as positional arguments in preparation for dropping explicit padding_token, bos_token and eos_token arguments in favor of the general kwargs handling of https://github.com/dmlc/gluon-nlp/pull/732.
``` python
nlp.Vocab({'a':10}, None, 1, '<unk>', 'PAD')  # deprecated and will be unsupported
nlp.Vocab({'a':10}, None, 1, '<unk>', padding_token='PAD')  # recommended use
``` 
- We need to consider if we want to deprecate the current default values of padding, bos and eos_token as well in the future. Ie. if `Vocab(counter)` should still create `Vocab(size=5, unk="<unk>", reserved="['<pad>', '<bos>', '<eos>']")` or maybe `Vocab(size=2, unk="<unk>", reserved="[]")` The advantage is that there is nothing special about these 3 special tokens compared to other application …

[DEV] Deprecate specifying Vocab padding, bos and eos_token as positional arguments

---

scripts/bert/data/dataloader.py

[WIP][BUGFIX] Fix a data sampling bug in BERT pre-training

---

docs/_static/custom.css
docs/_static/hidebib.js
docs/_static/install-options.js
docs/conf.py
docs/index.rst
docs/install.rst
docs/install/install-include.rst
docs/install/install-more.rst
tests/unittest/test_datasets.py

update installation guide by adopting the selectors from CV

[DOC] update installation guide with selectors

---

src/gluonnlp/model/attention_cell.py

For implementing a pointer mechanism in sequence to sequence models it is very practical to re-use attention cells. For example see the Attention-Based Copy Mechanism described in Jia, Robin, and Percy Liang. "Data recombination for neural semantic parsing." arXiv preprint arXiv:1606.03622 (2016).
The proposal is to additionally return the raw attention scores in the AttentionCell.
- The change is a backward compatible

[FEATURE] Add raw attention scores to the AttentionCell #951

---

docs/examples/machine_translation/gnmt.md
scripts/machine_translation/gnmt.py
scripts/machine_translation/inference_transformer.py
scripts/machine_translation/train_gnmt.py
scripts/machine_translation/train_transformer.py
scripts/tests/test_encoder_decoder.py
src/gluonnlp/model/seq2seq_encoder_decoder.py
src/gluonnlp/model/train/__init__.py
src/gluonnlp/model/transformer.py
src/gluonnlp/model/translation.py
tests/unittest/test_models.py

In the current Gluon API, each HybridBlock has to serve one puropse and can only
define a single callable interface. Previous Seq2SeqDecoder interface required
each Seq2SeqDecoder Block to perform two functionalities (multi-step ahead and
single-step ahead decoding). This means neither of the two functionalities can
in practice be hybridized completely. Thus use two separate Blocks for the two
functionalities. They may share parameters.
Update the NMTModel API accordingly.
Further refactor TransformerDecoder to make it completely hybridizable.
TransformerOneStepDecoder still relies on a small hack but can be hybridized
completely when we enable numpy shape semantics.

[Refactor] TransformerDecoder

---

scripts/language_model/transformer/transformer.py

[DOC] Adding documentation to xlnet scripts

---

docs/api/modules/model.rst
scripts/language_model/transformer/transformer.py
scripts/tests/test_scripts.py
scripts/text_generation/model/gpt.py
src/gluonnlp/model/bert.py
src/gluonnlp/model/block.py
src/gluonnlp/model/transformer.py

Split up inheritance structure of TransformerEncoder and BERTEncoder
- Removes `BERTLayerNorm` and `BERTPositionwiseFFN`
- Changes the `layer_norm_eps=None` default to `layer_norm_eps=1e-5` for Transformer models and `layer_norm_eps=1e-12` for BERT models. The distinction was previously done by using `BERTLayerNorm` vs `nn.LayerNorm`.
cc @dmlc/gluon-nlp-team @fierceX

[Refactor] Split up inheritance structure of TransformerEncoder and BERTEncoder

---

env/cpu/py3-master.yml
env/gpu/py3-master.yml

[CI] Disable known bad mxnet nightly version

---

scripts/machine_translation/train_gnmt.py
scripts/machine_translation/train_transformer.py

Fix version check in train_gnmt.py and train_transformer.py
Fixes https://github.com/dmlc/gluon-nlp/issues/1002

Fix version check in train_gnmt.py and train_transformer.py

---

pytest.ini
scripts/tests/test_scripts.py
scripts/text_generation/model/gpt.py
scripts/text_generation/sequence_sampling.py

Fixes #993 
Fixes #1015
cc @dmlc/gluon-nlp-team @gigasquid

Make GPT2Model a HybridBlock

---

scripts/language_model/conversion_utils/compare_transformerxl_pytorch_gluon_model.py
scripts/language_model/conversion_utils/compare_xlnet_pytorch_gluon_model.py
scripts/language_model/transformer/model.py
scripts/language_model/transformer/transformer.py
setup.py

We previously asserted that our implementation computes the same result as the pytorch-transformers implementation. However, that implementation was wrong up until 1.2.0 release in which their implementation was fixed unintentionally / by accident in https://github.com/huggingface/transformers/pull/1089/#issuecomment-526154630.
This also updates the comparison scripts which broke to API breakage in the packages that we compare to (renaming / reordering of arguments etc.).
Also updates `gelu` to `approx_gelu` in the XLNet pretrained model configuration, which should have been done in #988.
@zburning FYI

[Bugfix] TransformerXL LayerNorm eps and XLNet pretrained model config

---

.pytype.cfg
Makefile
env/cpu/py3-master.yml
env/docker/py3.yml
env/gpu/py3-master.yml
src/gluonnlp/base.py
src/gluonnlp/data/__init__.py
src/gluonnlp/data/batchify/__init__.py
src/gluonnlp/data/batchify/batchify.py
src/gluonnlp/data/batchify/embedding.py
src/gluonnlp/data/conll.py
src/gluonnlp/data/corpora/google_billion_word.py
src/gluonnlp/data/stream.py
src/gluonnlp/embedding/__init__.py
src/gluonnlp/embedding/token_embedding.py
src/gluonnlp/initializer/__init__.py
src/gluonnlp/loss/__init__.py
src/gluonnlp/metric/__init__.py
src/gluonnlp/model/sequence_sampler.py
src/gluonnlp/optimizer/__init__.py
src/gluonnlp/utils/__init__.py
src/gluonnlp/utils/parallel.py
src/gluonnlp/vocab/vocab.py

Pytype is a static type analyzer for Python code.
> Pytype checks and infers types for your Python code - without requiring type annotations. Pytype can:
> 
>  - Lint plain Python code, flagging common mistakes such as misspelled attribute names, incorrect function calls, and much more, even across file boundaries.
> - Enforce user-provided type annotations. While annotations are optional for pytype, it will check and apply them where present.
> - Generate type annotations in standalone files ("pyi files"), which can be merged back into the Python source with a provided merge-pyi tool.
> 
> Pytype is a static analyzer; it does not execute the code it runs on.
Later we can use the `merge-pyi` to integrate the inferred types into the codebase.

[CI] Enable type checks and inference with pytype

---

scripts/bert/pretraining_utils.py

With multiple dataloaders created with multi-processing, mpi sometimes crashes. This affects users who use horovod for bert pre-training. Temporarily disable multi-processing before the new version of dataloader is available. 

Disable multi-processing in bert pre-training dataloader

---

scripts/machine_translation/train_transformer.py

[MAINTENANCE]This fix replaces magic numbers with the name
- [X ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)
- [ X] Changes are complete (i.e. I finished coding on this PR)
- [ X] All changes have test coverage
- [ X] Code is well-documented

Improve the readability of the training script. 

---

scripts/question_answering/data_pipeline.py
setup.py

Because a nlp.data.SpacyTokenizer is created as class attribute, SpacyTokenizer
is required when Python parses the data_pipeline.py file. This means users will
always need to install the "optional" SpacyTokenizer dependencies, even if they
don't plan to use it. For example, just running an unrelated test in the scripts
folder will currently raise the following error.
```
ImportError while loading conftest '/home/ubuntu/projects/gluon-nlp/scripts/tests/conftest.py'.
scripts/tests/conftest.py:23: in <module>
from ..question_answering.data_pipeline import SQuADDataPipeline
scripts/question_answering/data_pipeline.py:433: in <module>
class SQuADDataTokenizer:
scripts/question_answering/data_pipeline.py:435: in SQuADDataTokenizer
spacy_tokenizer = nlp.data.SpacyTokenizer() …
```

Fix scripts/question_answering/data_pipeline.py requiring optional package

---

scripts/bert/fp16_utils.py

Fixes https://github.com/dmlc/gluon-nlp/issues/1034

[BUGFIX] Fix dtype mismatch for NaN check 

---

ci/batch/submit-job.py

switch batch jobs to use g4dn.2x instance. the updated job definition reduces allocated memory from 40G to 30G since g4dn.2x has 32G memory

[CI] switch batch jobs to use G4dn.2x instance

---

ci/batch/docker/Dockerfile
env/cpu/py3-master.yml
env/docker/py3.yml
env/gpu/py3-master.yml
scripts/parsing/parser/biaffine_parser.py
src/gluonnlp/model/train/cache.py

[CI] Backport #991, #997 to 0.8.x branch

---

src/gluonnlp/model/attention_cell.py

To circumvent https://github.com/apache/incubator-mxnet/issues/17056 which causes bert distributed training to diverge 

[BUGFIX] avoid using dict for attention cell parameter creation

---

scripts/language_model/word_language_model.py

There is a unicode comma in the print statement. It needed to be replaced with an ASCII comma.
Fixes #1055

[BUGFIX] unicode comma fix

---

docs/examples/sentence_embedding/bert.md
src/gluonnlp/data/sampler.py
tests/unittest/test_sampler.py

Add an option to ensure all partitions have the same number of samples. It will add extra samples if needed, like what torch DistributedSampler does. 
@rich-junwang
Example:
```
sampler = SplitSampler(len(train_dataset), num_workers, rank, even_size=True)
train_iter = gluon.data.DataLoader(train_dataset, batch_size=batch_size, sampler=sampler)
```

[Feature] add even_size option to split sampler

---

README.rst
scripts/bert/finetune_ner.py
scripts/bert/finetune_squad.py
src/gluonnlp/utils/parameter.py

The doc is wrong. Updated to 1.6.

[DOC] update mxnet version in installation doc

---

env/cpu/py3-master.yml
env/cpu/py3.yml
env/docker/py3.yml
env/gpu/py3-master.yml
env/gpu/py3.yml
scripts/bert/index.rst
scripts/natural_language_inference/index.rst

[DOC] remove py3 usage from the doc

---

ci/jenkins/Jenkinsfile_py3_cpu_unittest
ci/jenkins/Jenkinsfile_py3_gpu_integration
ci/jenkins/Jenkinsfile_py3_gpu_unittest
env/cpu/py3-master.yml
env/cpu/py3.yml
env/docker/py3.yml
env/gpu/py3-master.yml
env/gpu/py3.yml
src/gluonnlp/data/transforms.py
src/gluonnlp/data/utils.py
src/gluonnlp/data/word_embedding_evaluation.py
src/gluonnlp/embedding/token_embedding.py

Enable CI for MXNet 1.6 pre-release. We need to ensure that our code remains compatible with MXNet 1.6. Currently we're only testing against MXNet 1.7 pre-release version.
Based on a manual build uploaded to my S3 bucket. There are currently no public builds of MXNet 1.6 pre-release available.

[CI] Enable CI for MXNet 1.6 pre-release

---

src/gluonnlp/model/block.py

[Block] Use fused gelu operator

---

scripts/language_model/index.rst

Training cmd of AWD-LSTM is not consistent with log.

[DOC] Fix Language Modeling index.rst 

---

scripts/machine_translation/train_gnmt.py

Modify the log average loss during training and validation proposed in #1102 .
Fixes #1102.
The log message looks like:
```
2020-01-08 08:53:50,968 - root - [Epoch 0 Batch 100/1043] loss=6.4215, ppl=614.9522, gnorm=0.7030, throughput=39.15K wps, wc=606.57K
2020-01-08 08:54:04,325 - root - [Epoch 0 Batch 200/1043] loss=5.8612, ppl=351.1320, gnorm=0.3394, throughput=43.74K wps, wc=584.18K
2020-01-08 08:54:17,698 - root - [Epoch 0 Batch 300/1043] loss=5.4339, ppl=229.0387, gnorm=0.3442, throughput=44.33K wps, wc=592.78K
2020-01-08 08:54:30,365 - root - [Epoch 0 Batch 400/1043] loss=5.0884, ppl=162.1247, gnorm=0.3193, throughput=45.10K wps, wc=571.26K
2020-01-08 08:54:42,646 - root - [Epoch 0 Batch 500/1043] loss=4.8152, ppl=123.3674, gnorm=0.3304, throughput=45.15K wps, wc=554.48K
2020-01-08 …
```

[BUGFIX] modify the log average loss

---

src/gluonnlp/model/train/language_model.py

Resolve the conflict between weight sharing and weight tied. 
Fixes #1086
Running the code below:
```python
model = nlp.model.train.AWDRNN(args.model, len(vocab), args.emsize, args.nhid, args.nlayers,
args.tied, args.dropout, args.weight_dropout,
args.dropout_h, args.dropout_i, args.dropout_e)
model_eval = nlp.model.AWDRNN(args.model, len(vocab), args.emsize, args.nhid, args.nlayers,
args.tied, args.dropout, args.weight_dropout,
args.dropout_h, args.dropout_i, args.dropout_e,
params=model.collect_params())
model.initialize(mx.init.Xavier(), ctx=context)
model.hybridize(static_alloc=True)
print(model)
def check_initialized(net):
params = net.collect_params()
for param in params:
try:
params[param].list_ctx()
except RuntimeError:
return False
return True
print(check_initialized(model)) …
```

[BUGFIX] fix the weight tied and weight sharing collision error

---

src/gluonnlp/model/sampled_block.py
tests/unittest/test_sampled_logits.py

Support int32 candidate ids and labels for NCE/IS blocks. 

[BugFix] support int32 for sampled blocks

---

src/gluonnlp/data/utils.py
src/gluonnlp/utils/files.py
tests/unittest/test_datasets.py

Acquire a file lock before downloading the dataset. This helps when using multi-processing for multi-GPU training, or multi-machine training with a shared file system 

[Parallel] Avoid race condition when downloading datasets

---

src/gluonnlp/optimizer/bert_adam.py
tests/unittest/test_optimizer.py

FEATURE: multi-tensor Update - Adam Optimizer

Adam multitensor

---

scripts/machine_translation/inference_transformer.py

This PR is to update the default transformer pre-trained model to the link of [e25287c5](http://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/transformer_en_de_512_WMT2014-e25287c5.zip) to align with [website](https://gluon-nlp.mxnet.io/master/model_zoo/machine_translation/index.html#transformers).
@leezu @eric-haibin-lin

[SCRIPTS]update pre-trained model link for transformer

---

scripts/bert/fp16_utils.py
scripts/bert/run_pretraining.py
scripts/tests/test_scripts.py

Add support for custom optimizer. Fix checkpoint interval check. 

[Script] Minor enhancement for bert pre-training script 

---

scripts/language_model/large_word_language_model.py
src/gluonnlp/model/train/language_model.py

There is a `class ParallelBigRNN` defined in the `large_word_language_model.py` script. I think it should be merged to the model api like `class ParallelTransformer`. Additionally, I need to reuse this class in some estimator api.

[MAINTENANCE] Move ParallelBigRNN into model api

---

scripts/bert/fp16_utils.py
src/gluonnlp/utils/parameter.py
tests/unittest/test_utils.py

Make use of multi-tensor sum of squares during the computation of the norm in bert training.
If multiple contexts/devices are available, the tensors are distributed among them, and later they are reduced into a single scalar.

FEATURE Bert fp16 norm: multi-tensor sum_sq

---

src/gluonnlp/model/train/language_model.py
tests/unittest/test_model_weight_share.py

This fix addresses the standard RNN weight tied/weight sharing conflict.  PR https://github.com/dmlc/gluon-nlp/pull/1087 fixed weight sharing error of `AWDRNN`. This  PR fixes the `standardRNN`.

[BUGFIX] fix standard rnn weight sharing error

---

scripts/bert/finetune_classifier.py
scripts/tests/test_bert_checkpoints.py
src/gluonnlp/model/bert.py
src/gluonnlp/utils/files.py

[API] use softmax with length, and interleaved matmul for BERT

---

env/cpu/py3-master.yml
env/gpu/py3-master.yml

[CI] Update MXNet master version tested on CI (#1113)

---

src/gluonnlp/vocab/vocab.py
tests/unittest/test_vocab_embed.py

[BUGFIX] Fix vocab determinism in py35 (#1166)

---

scripts/language_model/model/qa.py

Fix the typo in question answering script of xlnet. The hidden units of xlnet large is 1024 which confilts with the fixed in_channels 768. see [#17654](https://github.com/apache/incubator-mxnet/issues/17654).
@leezu @zburning 

[BUGFIX] fix the in_channels of LN in qa script

---

docs/md2ipynb.py

As we want to simplify the process of compiling the docs and website manually on a laptop machine without GPU (e.g. MacBook Pro), we want a command that can disable computing python scripts in the docs. 
This pull request is a standalone change to the interface of md2ipynb file that supports converting without computing python scripts. 
This change is compatible with all the existing CI and Makefile. It accepts existing commands and enables computing on default. 

Add a general interface in md2ipynb for disable computing

---

Makefile

As we want to simplify the process of compiling the docs and website manually on a laptop machine without GPU (e.g. MacBook Pro), we want a command that can disable computing python scripts in the docs.
This pull request is a standalone change to the interface of Makefile that supports converting without computing python scripts.
This change is compatible with all the existing CI and Makefile. It accepts existing commands and enables computing on default.
After this change, you can make the docs without computing the python scripts by using the following command:
```
make docs MD2IPYNB_OPTION =-d
```
What's more, you can still use the default command `make docs` to run the python scripts as before.
This change relies on the previous change #1191 
- If this change is a backward …

[DOC]Add a new argument to Makefile for making docs without computing

---

docs/md2ipynb.py

This is a **bug fix**, rather than an **enhancement**.
Currently this file is invoked smoothly from CI, because CI passes the full path as the argument to this python script. However, when invoked from Makefile, using the command `make docs`, only file name is passed to this file, resulting in the `input_dir` variable to be empty string, so that the `os.chdir()` will fail.
More detailed explanation:
When we use `make docs`, the L60 of `Makefile` will be executed, and then L86 of `Makefile` will be executed. See in L89, variable `BASENAME` will be the file name and variable `DIR` will be the directory. In L96, only `BASENAME` is passed to `MD2IPYNB` as an argument. So there will be error in the python file.
With this fix, the python script doesn't need to change directory explicitly …

[BUGFIX]Fix chdir Error when invoked from Makefile

---

Makefile

This is a **bugfix** for `Makefile`. 
This pull request doesn't affect CI.
Please see [L77 in ci/jenkins/Jenkinsfile_py3-master_gpu_doc](https://github.com/dmlc/gluon-nlp/blob/f092e60c1141ab4c5ea01a2b25d90ff3aedc857b/ci/jenkins/Jenkinsfile_py3-master_gpu_doc#L77) and [L110 in ci/jenkins/Jenkinsfile_py3-master_gpu_doc](https://github.com/dmlc/gluon-nlp/blob/f092e60c1141ab4c5ea01a2b25d90ff3aedc857b/ci/jenkins/Jenkinsfile_py3-master_gpu_doc#L110), we are using `python3` in CI and it is working well.
But in `Makefile`, we are using `python`. I have tried both on my laptop and the server and found out that this can lead to a fatal error with `python2` in this python script. The error is raised in L30 of the `md2ipynb.py` with the function `open()`. Please see the error log below.
If I change …

[BUGFIX]Change to python3 to invoke MD2IPYNB in Makefile

---

docs/conf.py

There are cases that we don't want to compute the results for the `python` code chunks in the `.md` files. So I added a configuration for disabling execute code chunks when converting `.md` files to `.ipynb` files. See #1191 #1192 
However, the `nbsphinx` plugin of `sphinx`, which is in charge of reading `.ipynb` files for `sphinx`, automatically executes all chunks without output, which is opposite to what we want. So this pull request turns this feature off.
Turning this off won't have any side effect because all the `ipynb` files in this project resides in the `docs/examples/` path and they are all converted from `md` files. So even if we want to compute the results, all the computation should be done in `md2ipynb.py` file and `nbsphinx` will still not compute code chunks in the normal …

[BUGFIX]Disable nbsphinx plugin execute code chunks

---

Makefile

Currently the `distribute` part of the `Makefile` is using `python` engine, which will lead to the following errors. Changing to `python3` will fix this problem
```
File "setup.py", line 95, in <module>
Extension('gluonnlp.data.fast_bert_tokenizer', sources=['src/gluonnlp/data/fast_bert_tokenizer.pyx']),
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
_setup_distribution = dist = klass(attrs)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 268, in __init__
self.fetch_build_eggs(attrs['setup_requires'])
File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 313, in fetch_build_eggs
replace_conflicting=True,
File …
```

[BUGFIX] Change distribute interpreter to python3

---

Makefile

I am using PyCharm for developing. I often use `make docs` to preview the newly built website files and use `make clean` to wipe all the artifacts out.
However, the `make clean` command removes everything in the `./idea` folder, which is very unfriendly and destructive, meaning that I will need to manually set all the settings and preferences for this project.
I think the change in this pull request will benefit the PyCharm users who build the website.

[BUGFIX]Exclude .idea from make clean

---

Makefile

Currently, the L62 to L81 in the old Makefile is preventing users from building the website locally. It gives the following errors:
```
for f in docs/examples/word_embedding/word_embedding_training.md docs/examples/word_embedding/word_embedding.md docs/examples/machine_translation/transformer.md docs/examples/machine_translation/gnmt.md docs/examples/sentence_embedding/elmo_sentence_representation.md docs/examples/sentence_embedding/bert.md docs/examples/language_model/train_language_model.md docs/examples/language_model/use_pretrained_lm.md docs/examples/sentiment_analysis/sentiment_analysis.md docs/examples/sentiment_analysis/self_attentive_sentence_embedding.md docs/examples/sequence_sampling/sequence_sampling.md ; do \
FILE=`echo $f | sed 's/docs\///g'` ; \
DIR=`dirname $FILE` ; \ …
```

[FEATURE]Add new command for building website locally

---

src/gluonnlp/model/bert.py

https://github.com/dmlc/gluon-nlp/issues/1183#issuecomment-621659400

Fix layer_norm_eps in BERTEncoder

---

ci/batch/submit-job.py

[BUGFIX] Fix deprecation warnings due to invalid escape sequences.

---

ci/jenkins/Jenkinsfile_py3-master_cpu_unittest
ci/jenkins/Jenkinsfile_py3_cpu_unittest

Here is a brief statistics of the CI time out occurrences:
Among the 25 most recent CI builds the following CI items has such **_rate of time out_**(excluding failures):
cpu-unittest: 45%
master-cpu-unittest: 33%
gpu-integration: 0%
gpu-unittest: 0%
master-gpu-doc: 0%
master-gpu-integration: 0%
master-gpu-unittest: 0%
Therefore, I am lifting the time out settings for cpu-unittest and master-cpu-unittest so that they can provide steady performance even on peak hours.

[CI] Lift timeout on cpu unittest

---

docs/examples/sentiment_analysis/self_attentive_sentence_embedding.md

[BUGFIX] Change sklearn accuracy metric to mxnet accuracy metric

---

scripts/sentiment_analysis/process_data.py
scripts/sentiment_analysis/sentiment_analysis_cnn.py

[BUGFIX] TextCNN rand model downloads pretrained vectors even if not needed

---

scripts/bert/finetune_squad.py

The command for finetune_squad.py was originally using adam without wd. Removing it from the script. Fixes #1204 https://github.com/dmlc/gluon-nlp/pull/1211 

 [v0.9][BUGFIX] Fix wd in finetune_squad.py

---

scripts/tests/test_models.py
scripts/text_generation/model/gpt.py
src/gluonnlp/model/bert.py
src/gluonnlp/model/language_model.py
src/gluonnlp/model/transformer.py
tests/unittest/test_models.py

This commit removes the mutable_args restriction.
After this commit, any parameter can be overriden,
as long as the user sets the allow_override parameter
to True.

[BUGFIX] Remove mutable_args restriction in get_model API

---

src/gluonnlp/data/conll.py

[BUGFIX] Change CONLL dataset source to HTTPS

---

scripts/machine_translation/train_gnmt.py
scripts/machine_translation/train_transformer.py

[BUGFIX] Remove test set from validation

---

docs/md2ipynb.py

Lift timeout restriction per notebook to 90 minutes
This pull request serves for #1230 

[Website] Lift timeout restriction per notebook to 90 minutes

---

.github/workflows/unittests.yml
tools/batch/docker/Dockerfile
tools/batch/docker/gluon_nlp_job.sh
tools/batch/submit-job.py
tools/batch/wait-job.py

AWS batch job tool for GluonNLP
- This PR contains the batch job setup for the existing account. I'm working on a second part that is self-contained with cloudformation template and can be used in any account.

[CI] AWS batch job tool for GluonNLP (Part I)

---

scripts/question_answering/run_squad.py
src/gluonnlp/attention_cell.py
src/gluonnlp/models/bert.py

Adding FP16 in QA-BERT inference
cc @dmlc/gluon-nlp-team, @sxjscience

Add fp16 support for Bert QA inference

---

tools/batch/docker/Dockerfile
tools/batch/docker/gluon_nlp_job.sh
tools/batch/submit-job.py

update the numpy branch to use the new set of batch setup.
- I replicated the setup in the gluonnlp-dev account so that it doesn't affect the previous setup.

[CI] update batch to gluonnlp-dev

---

scripts/datasets/general_nlp_benchmark/prepare_glue.py
scripts/question_answering/run_squad.py

Fix SQuAD due to the recent upgrade of MXNet: https://github.com/apache/incubator-mxnet/pull/18368 @MoisesHer Basically, the default data type of integer arrays will be int64.

[Numpy] Fix SQuAD + Fix GLUE downloading

---

scripts/datasets/pretrain_corpus/prepare_openwebtext.py

The current implementation will raise `TypeError: 'NoneType' object is not iterable`, since `random.shuffle()` shuffles the input in place and returns `None`.
cc @szhengac @sxjscience 

fix prepare_openwebtext

---

src/gluonnlp/model/bert.py

Fixes https://github.com/dmlc/gluon-nlp/issues/1183 https://github.com/dmlc/gluon-nlp/issues/1294 
@davisliang @kaonashi-tyc 

Fix attn bias

---

CODEOWNERS
CODE_OF_CONDUCT.md
LICENSE
README.md
src/gluonnlp/__init__.py
tests/test_models_bert.py
tools/batch/README.md
tools/batch/docker/Dockerfile
tools/batch/hello_world.py
tools/batch/submit-job.py
tools/docker/README.md
tools/docker/devel_entrypoint.sh
tools/docker/start_jupyter.sh
tools/docker/ubuntu18.04-devel-gpu.Dockerfile

```
docker pull gluonai/gluon-nlp:v1.0.0
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 gluonai/gluon-nlp:v1.0.0
```
@dmlc/gluon-nlp-committers 
Should solve https://github.com/dmlc/gluon-nlp/issues/1243 and https://github.com/dmlc/gluon-nlp/issues/1139

[Numpy] Fix AWS Batch + Add Docker Support

---

setup.py
src/gluonnlp/__init__.py

automatically generate date suffix for dev versions

[DEV] automatically generate date suffix for dev versions

---

scripts/pretraining/pretraining_utils.py

[DOC]fix typo

---

scripts/pretraining/pretraining_utils.py

Fix the dynamic mask sampling strategy. Fix Issue #1321 

[BUGFIX] fix valid candidates issue

---

scripts/datasets/general_nlp_benchmark/prepare_glue.py
src/gluonnlp/layers.py
src/gluonnlp/models/__init__.py
src/gluonnlp/models/albert.py
src/gluonnlp/models/bart.py
src/gluonnlp/models/bert.py
src/gluonnlp/models/electra.py
src/gluonnlp/models/mobilebert.py
src/gluonnlp/models/transformer.py
src/gluonnlp/utils/misc.py
src/gluonnlp/utils/parameter.py
src/gluonnlp/utils/preprocessing.py
tests/README.md
tests/test_layers.py
tests/test_models.py
tests/test_utils_misc.py

Some minor doc + API improvements.

[Fix] Some minor fixes for AMLC Tutorial

---

conftest.py

Otherwise all tests with `ctx` argument are skipped if no `ctx` is specified on the command line.

Set default ctx in conftest

---

.github/workflows/unittests-gpu.yml

Get `HTTP 400`  response code and error message `pr must match pattern ^(\d+|false|null|undefined|true)$` when uploading code coverage report for all the pull requests in GPU CI workflow. 
Probably because we are using `pull_request_target` event to deal with PR in GPU CI workflow and `GITHUB_REF` always refers to `refs/head` rather than format `refs/pull/#/merge`, which means it's not possible for codecov-action to get the pr number from `GITHUB_REF`. 
As suggested in [this issue](https://github.com/codecov/codecov-action/issues/69), we can customize the step for uploading code coverage in `pull_request_target` event. 

[CI][BUGFIX] Custom Step for Uploading Code Coverage in Pull Request Event

---

scripts/datasets/machine_translation/wmt2014_ende_base.sh
scripts/machine_translation/README.md
scripts/machine_translation/wmt2014_back_translation.sh
src/gluonnlp/cli/average_checkpoint.py
tests/process_cli/test_average_checkpoint.py
tests/test_models.py

[FEATURE]Update readme of nmt

---

.github/workflows/buildwebsite.yml

Improve workflow for building documentation website. 

[Website] Improve website build workflow

---

ci/prepare_clean_env.sh

Workaround installation issue of Horovod on CI after upstream change of build system:
```
[2020-10-05T21:42:25.859Z]     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -m64 -fPIC -fPIC -std=c++11 -fPIC -O3 -Wall -fassociative-math -ffast-math -ftree-vectorize -funsafe-math-optimizations -mf16c -mavx -mfma -I/var/lib/jenkins/workspace/gluon-nlp-gpu-py3-master/conda/gpu/py3-master/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
[2020-10-05T21:42:25.859Z]     cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[2020-10-05T21:42:25.859Z]     gcc -pthread -shared …
```

Build horovod with gloo

---

scripts/question_answering/run_squad.py

We should additionally normalize the loss by `num_accumulated * len(ctx_l)`. I observed this issue since the grad_norm in the finetune log is very large (around 70), while in the pretraining log it is usually around 2.
To see why the current version is wrong intuitively, consider two commands `python3 run_squad.py --batch_size 12 --num_accumulated 1 ...` and `python3 run_squad.py --batch_size 1 --num_accumulated 12 ...`, they should give the same results when using MXNet Trainer. But this is not true currently, by `print(total_norm)`, you can observe that the grad_norm is much larger (nearly 10 times) in the second command than the first command. Meanwhile, note that the other operations (`clip_grad_global_norm` and `trainer.update`) are the same across these two commands, thus the …

fix squad loss

---

docs/examples/question_answering/squad_utils.py
scripts/question_answering/models.py
src/gluonnlp/layers.py
src/gluonnlp/models/albert.py
src/gluonnlp/models/bert.py
src/gluonnlp/models/electra.py
src/gluonnlp/models/gpt2.py
src/gluonnlp/models/mobilebert.py
src/gluonnlp/models/roberta.py
src/gluonnlp/models/transformer.py
src/gluonnlp/models/transformer_xl.py
tests/test_utils_misc.py
tests/test_utils_parameter.py
tools/docker/gluon_nlp_job.sh
tools/docker/ubuntu18.04-gpu.Dockerfile

As title. No longer needed as of https://github.com/apache/incubator-mxnet/commit/3d1df4e035077b5d4de859e7bf464181388d47a0

Remove gluonnlp.layers.HybridSequential

---

docs/Makefile

Currently, GluonNLP CI for docs building will always fail because of the following errors. 
`WARNING: the mxtheme extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit`
`WARNING: doing serial read`
We may have two possible solutions. 
1. Disable parallel building.  
2. Update `mxtheme` extension to make parallel read safe. 
This PR will disable parallel building to remove these warnings. 

[DOC] Remove warnings

---

docs/_static/gluon-logo.svg

adjust logo size to reduce the margin

[WEBSITE] adjust logo size

---

.github/workflows/buildwebsite.yml
.github/workflows/unittests.yml
README.md
tools/docker/gluon_nlp_job.sh
tools/docker/ubuntu18.04-cpu.Dockerfile
tools/docker/ubuntu18.04-gpu.Dockerfile

[Docker] Update Docker

---

scripts/benchmarks/benchmark_hf.py

I noticed that we need to manually disable multiprocessing.
Also, the original huggingface benchmark has not called `torch.cuda.synchronize()`. The comparison won't be fair because the CUDA calls are async. I added the `torch.cuda.synchronize()` in the benchmarking script. (See HF implemenation https://github.com/huggingface/transformers/blob/ab17758874f62c03b6e5627f846a697920b16dd8/src/transformers/benchmark/benchmark.py#L171-L194).
@Cli212

[Benchmark] Update HuggingFace benchmarking

---

setup.py
src/gluonnlp/base.py
src/gluonnlp/utils/lazy_imports.py
src/gluonnlp/utils/misc.py
tests/test_utils_misc.py

Rely on boto3 by default for downloads from S3. Handle unauthenticated access to S3 via botocore if needed.

Speed up downloads from S3 bucket

---

src/gluonnlp/op.py
tests/test_layers.py

This version aligns the implementation of relative position encoding with that in mesh_tensorflow. It would also help program T5 model in the future. 
- Define relative position as `mem_i - query_j` in lieu of previous `query_i - mem_j `
- Rephrase documentation

adjust implementation of relative position encoding

---

scripts/datasets/question_answering/README.md
scripts/datasets/question_answering/prepare_naturalquestions.py
scripts/datasets/url_checksums/naturalquestions.txt

This PR commits the script for downloading NaturalQuestions from s3 bucket. And also, instructions for using this script is written in README.md.
Additionally, I found that if we want to download triviaqa data, we should use command```python3 prepare_triviaqa.py --type {rc,unfiltered}``` rather than ```python3 prepare_triviaqa.py --version {rc,unfiltered}```which README.md shows. So I update this part in README.md too. 

Add NaturalQuestions to datasets

---

tests/test_models_albert.py
tests/test_models_bert.py
tests/test_models_mobilebert.py
tests/test_models_roberta.py

In `test_bert.py` we assert about `mlm_score` instead of `mlm_scores` in the latter part of the test.
To avoid similar copy-paste errors in the future, consistently use `mlm_score` in the tests.

Fix typo in test_bert.py

---

src/gluonnlp/data/tokenizers/sentencepiece.py
src/gluonnlp/op.py
tests/test_data_tokenizers.py

This PR modifies the sanity check in SentencepieceTokenizer to ensure easier insertion of additional special tokens, which later would help add <extra_id>s corresponding to noise span sentinels as in T5 tokenizer. Accordingly, model and vocab for T5-base have been uploaded to S3 for some new test cases. 
- Relaxed spm sanity check
- Test cases for T5 tokenizer
- A Simple fix to an op.py docstring

[FEATURE] relax spm sanity check; add t5 tokenizer tests

---

src/gluonnlp/data/tokenizers/huggingface.py

Fix the huggingface wordpiece tokenizer. I noticed that the previous implementation may trigger a warning in AutoGluon.

[Tokenizer] Fix huggingface wordpiece warning

---

tools/batch/batch_states/test_data_pipeline.sh

It seems that the test is still failing so I'm submitting this PR.

[Fix] Try to fix data pipeline scheduled test (attempt 2)

---

.github/workflows/unittests.yml
README.md
src/gluonnlp/utils/misc.py
src/gluonnlp/utils/tvm_utils.py
tests/test_models.py
tools/docker/gluon_nlp_job.sh
tools/docker/install/install_tvm_cpu.sh
tools/docker/install/install_tvm_gpu.sh
tools/docker/ubuntu18.04-cpu.Dockerfile
tools/docker/ubuntu18.04-gpu.Dockerfile

Fix issue #1425. Update docker and enable tvm test. 

[TVM] Fix Tvm Integration

---

.github/workflows/unittests-gpu.yml
.github/workflows/unittests.yml
setup.py
src/gluonnlp/utils/misc.py
tests/test_utils_misc.py
tools/docker/gluon_nlp_job.sh
tools/docker/ubuntu18.04-cpu.Dockerfile
tools/docker/ubuntu18.04-gpu.Dockerfile

add decorator for logging exceptions
- This is useful in debugging worker-side errors that can result in KeyError mentioned in #1505 

[MISC] add decorator for logging exceptions

---

scripts/generation/calculate_metrics.py

remove num_samples arguments in generation calculate_metrics. the number of samples can be inferred from the sample file.
- I removed num_bleu_samples together with num_samples, as it's unclear to me whether subsampling is needed when calculating self BLEU. Feel free to comment or suggest otherwise.

[SCRIPT] update default arguments and add seed for scripts/generation/calculate_metrics.py

---

src/gluonnlp/data/loading.py

Same workaround from https://github.com/apache/incubator-mxnet/pull/19925 for dataset loader in gluonnlp.

[BUGFIX] gc before fork in loader

---

scripts/bert/embedding.py

[BUGFIX] fix padding detection bug when processing out of vocabulary tokens.
The fix can handle zero valued padding_idx in RoBERTa model.
Fix padding detection bug when processing out of vocabulary tokens.
The fix can handle zero valued padding_idx in RoBERTa model.

[BUGFIX] fix padding detection bug when processing out of vocabulary tokens

---

scripts/bert/bertpass_gpu.cc
scripts/bert/deploy.py
scripts/bert/lib_api.cc
scripts/bert/setup.py

Change custom graph pass implementation to make it compatible with MXNet 1.8 
Solving issue https://github.com/dmlc/gluon-nlp/issues/1388
cc @dmlc/gluon-nlp-team, @samskalicky, @Kh4L

Make BERT-GPU deploy compatible with MXNet 1.8

---

.github/workflows/unittests.yml
docs/tutorials/deep_learning_compiler/tvm_basic.md
scripts/benchmarks/benchmark_utils.py
setup.py
tests/test_models.py
tools/docker/install/install_tvm_cpu.sh
tools/docker/install/install_tvm_gpu.sh
tools/docker/ubuntu18.04-gpu.Dockerfile

TVM will deprecate graph_runtime and use graph_executor. https://github.com/apache/tvm/blob/bf862d4c4355eae4f18d89b3b6b98ed0a2c18e9c/python/tvm/contrib/graph_runtime.py#L24-L29
When building gpu docker, the log shows 
```
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.7.1+cu102
ERROR: No matching distribution found for torch==1.7.1+cu102
```
So, I changed to torch==1.8.1+cu102 @leezu 
Also fix sacremoses version to <0.0.44, because the contributors of sacremoses didn't update their release for 0.0.44 on github. Updates will be tracked in #1548 
- If this change is a backward incompatible change, why must this change be …

[TVM][BUGFIX] Change graph_runtime to graph_executor & Fix MosesNormalizer

---

.github/workflows/nightly-test.yml

Add nightly test on MXNet2.0 nightly release. 

[CI] Add nightly test

---

tools/diagnose.py

Signed-off-by: Sheng Zha <zhasheng@amazon.com>
add back diagnose script used for issue reporting
- reported in #1549 

[TOOL] add back diagnose script

---

scripts/bert/index.rst
src/gluonnlp/model/bert.py

Signed-off-by: Sheng Zha <zhasheng@amazon.com>
fix dataset names for distilbert
- reported in #1549 

[BUGFIX] fix dataset names for distilbert

---

tests/test_op.py

Attempts to fix #1299 using statistical inference
- The test involves checking for truncation and also checking if the distribution was initially sampled from a gumbel distribution
- Since this attempts to remove truncation from the gumbel distribution, I'm not sure if the approach is correct. Requesting comments on the same

[TEST] Add statistical inference for Truncated Gumbel distribution

---

scripts/question_answering/albert_custom.yaml
scripts/question_answering/custom_strategy.py
scripts/question_answering/models.py
scripts/question_answering/run_squad.py
scripts/question_answering/run_squad_albert.py
setup.py

This PR adds an example of quantizing ALBERT base v2 model with the [Intel Neural Compressor](https://github.com/intel/neural-compressor) with a custom strategy. Script run_squad_albert.py is based on the run_squad.py file.
This change is based on this [PR](https://github.com/dmlc/gluon-nlp/pull/1581).

Added ALBERT v2 quantization with INC example
